#!/usr/bin/env python

import os

# Force qtpy to use PySide6
os.environ['QT_API'] = 'pyside6'

from PySide6.QtCore import QFileSystemWatcher, QTimer, Slot
from PySide6.QtGui import QPalette
from PySide6.QtWidgets import (QAbstractButton, QApplication, QMessageBox)

from qtpyvcp.widgets.form_widgets.main_window import VCPMainWindow
from qtpyvcp.utilities.settings import getSetting

# Setup logging
from qtpyvcp.utilities import logger

LOG = logger.getLogger("QtPyVCP." + __name__)

from qtpyvcp import actions

import resources_rc

VCP_DIR = os.path.dirname(os.path.abspath(__file__))
THEMES_DIR = "themes"

LIGHT_STYLESHEET_FILE = "light.qss"
DARK_STYLESHEET_FILE = "dark.qss"

from tnc.view_styles import (BACKGROUND_FILES, BACKGROUND_NAMES,
                             VIEW_STYLE_FILES, VIEW_STYLE_NAMES,
                             render_view_style, scale_rgba_alphas,
                             tint_color, tint_overlay)

# Theme registry: display name -> qss file. The `theme.name` setting stores
# the index of the selected name in THEME_NAMES. The non-cyan variants are
# generated by generate_themes.py from the canonical dark.qss / light.qss.
# "Dark White" / "Light Black" are the monochrome black/white pair.
THEME_NAMES = [
    "Dark Cyan", "Light Cyan",
    "Dark Magenta", "Light Magenta",
    "Dark Green", "Light Green",
    "Dark Amber", "Light Amber",
    "Dark Blue", "Light Blue",
    "Dark Orange", "Light Orange",
    "Dark White", "Light Black",
]
THEME_FILES = {
    "Dark Cyan": DARK_STYLESHEET_FILE,
    "Light Cyan": LIGHT_STYLESHEET_FILE,
    "Dark Magenta": "dark-magenta.qss",
    "Light Magenta": "light-magenta.qss",
    "Dark Green": "dark-green.qss",
    "Light Green": "light-green.qss",
    "Dark Amber": "dark-amber.qss",
    "Light Amber": "light-amber.qss",
    "Dark Blue": "dark-blue.qss",
    "Light Blue": "light-blue.qss",
    "Dark Orange": "dark-orange.qss",
    "Light Orange": "light-orange.qss",
    "Dark White": "dark-white.qss",
    "Light Black": "light-black.qss",
}

# Monochrome black/white pair: neutral palette text (no stray blue fallbacks).
MONO_THEMES = frozenset(("Dark White", "Light Black"))

# Accent rgb per theme (mirrors generate_themes.py ACCENTS). Used for the
# QPalette and for code-painted widgets (the frosted dialogs) so that no
# element stays hardcoded blue when a different accent is selected.
THEME_ACCENTS = {
    "Dark Cyan": (0, 229, 255), "Light Cyan": (0, 229, 255),
    "Dark Magenta": (255, 43, 214), "Light Magenta": (255, 43, 214),
    "Dark Green": (0, 255, 157), "Light Green": (0, 255, 157),
    "Dark Amber": (255, 179, 0), "Light Amber": (255, 179, 0),
    "Dark Blue": (41, 121, 255), "Light Blue": (41, 121, 255),
    "Dark Orange": (255, 115, 0), "Light Orange": (255, 115, 0),
    "Dark White": (242, 242, 242), "Light Black": (26, 26, 26),
}

# Updated on every theme apply; read by code-painted widgets (dialogs).
CURRENT_ACCENT = (0, 229, 255)
CURRENT_DARK = True
# Active view style (Neon, Flat, ..., Ink); read by code-painted widgets so
# the e-paper Ink style gets paper fills instead of accent-tinted glass.
CURRENT_STYLE = "Neon"


def glass_fill():
    """Top/bottom QColor pair for the frosted dialog fill, tinted toward the
    current accent so the dialog glass matches the selected theme. The fill
    alpha follows the panel-opacity setting. The Ink view style switches to
    near-opaque warm paper so the dialogs match the e-paper look."""
    from PySide6.QtGui import QColor
    factor = _opacity_setting('theme.panel-opacity', 100) / 100.0
    if CURRENT_STYLE == "Ink":
        alpha = round(252 * factor)
        return (QColor(247, 244, 236, alpha),
                QColor(236, 230, 218, alpha))
    ar, ag, ab = CURRENT_ACCENT
    alpha = round(228 * factor)
    top = QColor(round(22 + (ar - 22) * 0.22),
                 round(34 + (ag - 34) * 0.22),
                 round(54 + (ab - 54) * 0.22), alpha)
    bottom = QColor(round(13 + (ar - 13) * 0.10),
                    round(20 + (ag - 20) * 0.10),
                    round(34 + (ab - 34) * 0.10), alpha)
    return top, bottom


def glass_border():
    """Border QColor for the glass dialogs.

    The Ink style draws a flat ink-gray border instead of the neon accent so
    the dialogs match the e-paper look."""
    from PySide6.QtGui import QColor
    if CURRENT_STYLE == "Ink":
        return QColor(58, 58, 58, 220)
    ar, ag, ab = CURRENT_ACCENT
    return QColor(ar, ag, ab, 150)


def glass_glow():
    """(start, end) QColor pair for the dialogs' top-left soft glow.

    Ink uses a faint warm-paper shadow so no neon glow bleeds into the
    e-paper look; other styles keep the subtle accent glow."""
    from PySide6.QtGui import QColor
    if CURRENT_STYLE == "Ink":
        return QColor(120, 108, 88, 28), QColor(120, 108, 88, 0)
    ar, ag, ab = CURRENT_ACCENT
    return QColor(ar, ag, ab, 40), QColor(ar, ag, ab, 0)


def _opacity_setting(setting_id, default=100):
    """Int 0..255 from a persisted opacity setting (or default)."""
    try:
        setting = getSetting(setting_id)
        if setting is not None:
            return max(0, min(255, int(setting.getValue())))
    except Exception:
        pass
    return default


def glass_path(rect, cut=12):
    """QPainterPath with chamfered (cut) corners for the glass dialogs."""
    from PySide6.QtGui import QPainterPath
    path = QPainterPath()
    x0, y0, x1, y1 = rect.left(), rect.top(), rect.right(), rect.bottom()
    path.moveTo(x0 + cut, y0)
    path.lineTo(x1 - cut, y0)
    path.lineTo(x1, y0 + cut)
    path.lineTo(x1, y1 - cut)
    path.lineTo(x1 - cut, y1)
    path.lineTo(x0 + cut, y1)
    path.lineTo(x0, y1 - cut)
    path.lineTo(x0, y0 + cut)
    path.closeSubpath()
    return path

class MainWindow(VCPMainWindow):
    def __init__(self, *args, **kwargs):
        opts = kwargs.get('opts')
        self._develop_mode = bool(getattr(opts, 'develop', False))
        self._qss_watcher = None

        super(MainWindow, self).__init__(*args, **kwargs)

        self._connect_theme_tracking()
        self._apply_theme_stylesheet()

        self.initUi()

        # self.plot.camera.Zoom(0.002)
        # self.plot.setViewMachine()

    def _is_dark_theme(self):
        app = QApplication.instance()
        if app is None:
            return False
        palette = app.palette()
        window_lightness = palette.color(QPalette.Window).lightness()
        base_lightness = palette.color(QPalette.Base).lightness()
        return ((window_lightness + base_lightness) / 2) < 128

    def _diagnose_gcode_highlighting(self):
        """Ensure GCodeEditor syntax highlighting is properly configured.

        The framework applies YAML config via _apply_gcode_editor_yaml_config,
        but a timing issue can leave properties reset to their .ui file defaults
        on some editors. This runs late as a safety net, reading the same YAML
        config that the framework already loaded into qtpyvcp.CONFIG.
        """
        from PySide6.QtCore import QObject
        from PySide6.QtGui import QColor
        import qtpyvcp

        all_objs = self.findChildren(QObject)
        gcode_editors = [o for o in all_objs
                         if o.metaObject().className() in ('GCodeEditor', 'GcodeEditor')]

        if not gcode_editors:
            LOG.warning("No GCodeEditor widgets found")
            return

        # Read token→color map from YAML (same source as the framework uses)
        syntax_config = qtpyvcp.CONFIG.get('gcode_syntax_profile', {})
        token_color_map = {}
        for style in syntax_config.get('syntax_styles', []):
            color = style.get('color')
            if not color:
                continue
            qcolor = QColor(color)
            if not qcolor.isValid():
                continue
            for token in style.get('tokens', []):
                token_color_map[token] = qcolor

        # Read current-line style from YAML
        style_defaults = qtpyvcp.CONFIG.get('gcode_editor_style_defaults', {})
        cl_enabled = style_defaults.get('current_line_highlight_enabled', True)
        cl_bg = style_defaults.get('current_line_background', '#3a3a5a')
        cl_fg = style_defaults.get('current_line_color', '#d4d4d4')

        for editor in gcode_editors:
            name = editor.objectName()

            if token_color_map and hasattr(editor, 'setTokenColorMap'):
                se_enabled = editor.property('syntaxHighlightingEnabled')
                if not se_enabled:
                    LOG.warning("Editor '%s': syntaxHighlightingEnabled was False, forcing to True", name)
                editor.setTokenColorMap(token_color_map)
                editor.setProperty('syntaxHighlightingEnabled', True)
                LOG.info("Editor '%s': highlighting applied (%d token types)",
                         name, len(token_color_map))

            # Force-enable current-line highlight (same timing issue as above)
            cur_enabled = editor.property('currentLineHighlightEnabled')
            if not cur_enabled:
                LOG.warning("Editor '%s': currentLineHighlightEnabled was False, forcing to True", name)
            editor.setProperty('currentLineHighlightEnabled', bool(cl_enabled))
            editor.setProperty('currentLineBackground', QColor(cl_bg))
            editor.setProperty('currentLineColor', QColor(cl_fg))

    def _connect_theme_tracking(self):
        app = QApplication.instance()
        if app is None:
            return
        palette_changed = getattr(app, 'paletteChanged', None)
        if palette_changed is not None:
            try:
                palette_changed.connect(self._on_palette_changed)
            except Exception:
                LOG.exception("Failed to connect paletteChanged signal")

    def _on_palette_changed(self, *_args):
        QTimer.singleShot(0, self._apply_theme_stylesheet)

    def _apply_theme_stylesheet(self):
        global CURRENT_STYLE
        name, stylesheet_file = self._resolve_theme()
        style_name = self._resolve_style()
        CURRENT_STYLE = style_name
        app = QApplication.instance()
        if app is None:
            return
        try:
            # Palette first: exposes CURRENT_ACCENT / CURRENT_DARK (and
            # CURRENT_STYLE), which the view-style overlay renderer (and
            # code-painted widgets) use.
            self._apply_theme_palette(name)
            stylesheet_path = os.path.join(VCP_DIR, THEMES_DIR,
                                           stylesheet_file)
            with open(stylesheet_path, 'r', encoding='utf-8') as style_file:
                base_qss = style_file.read()
            style_path = os.path.join(VCP_DIR, THEMES_DIR,
                                      VIEW_STYLE_FILES[style_name])
            with open(style_path, 'r', encoding='utf-8') as style_file:
                overlay_qss = style_file.read()
            extra_tokens = None
            if style_name == "Ink":
                # absolute path to the paper checkmark the Ink checkbox uses
                extra_tokens = {"check_icon": os.path.join(
                    VCP_DIR, THEMES_DIR, "styles", "ink-check.svg")}
            overlay_qss = render_view_style(overlay_qss, CURRENT_ACCENT,
                                            CURRENT_DARK, extra_tokens)
            # background texture (optional) appended last, stretched to fill
            bg_rule = ""
            bg_file = BACKGROUND_FILES.get(self._resolve_background())
            if bg_file:
                bg_path = os.path.join(VCP_DIR, THEMES_DIR, bg_file)
                bg_rule = ("\n/* background texture */\nQMainWindow {\n"
                           "    border-image: url(%s) 0 0 0 0 stretch "
                           "stretch;\n}\n" % bg_path)
            # optional accent tint: a translucent wash on the central widget,
            # overlaying whatever background (texture or plain) is behind it.
            # Its alpha comes from the tint-opacity setting, untouched by the
            # panel-opacity scaling below.
            if self._background_tint_enabled():
                tr, tg, tb, _ta = tint_overlay(
                    CURRENT_ACCENT, CURRENT_DARK,
                    self._resolve_tint_color_hex())
                tint_alpha = _opacity_setting(
                    'theme.background-tint-opacity', 40)
                bg_rule += ("\n/* accent tint overlay */\n"
                            "QWidget#centralwidget {\n"
                            "    background: rgba(%d, %d, %d, %d);\n}\n"
                            % (tr, tg, tb, tint_alpha))
            # panel opacity: scale every translucent rgba fill in the sheet
            sheet = base_qss + "\n" + overlay_qss
            panel_opacity = _opacity_setting('theme.panel-opacity', 100)
            if panel_opacity < 100:
                sheet = scale_rgba_alphas(sheet, panel_opacity / 100.0)
            app.setStyleSheet(sheet + bg_rule)
            self._apply_gcode_editor_theme()
            self._apply_backplot_theme()
            if self._develop_mode:
                self._watch_stylesheet(stylesheet_path)
                self._watch_stylesheet(style_path)
                if bg_file:
                    self._watch_stylesheet(os.path.join(VCP_DIR, THEMES_DIR,
                                                        bg_file))
        except Exception:
            LOG.exception("Failed to load theme stylesheet: %s",
                          stylesheet_path)

    def _resolve_style(self):
        """Return the view-style display name for the persisted setting."""
        try:
            setting = getSetting('theme.style')
            if setting is not None:
                value = setting.getValue()
                if isinstance(value, int) and 0 <= value < len(VIEW_STYLE_NAMES):
                    return VIEW_STYLE_NAMES[value]
                if value in VIEW_STYLE_FILES:
                    return value
        except Exception:
            LOG.exception("Failed to read theme.style setting")
        return "Neon"

    def _resolve_background(self):
        """Return the background texture display name for the setting."""
        try:
            setting = getSetting('theme.background')
            if setting is not None:
                value = setting.getValue()
                if isinstance(value, int) and 0 <= value < len(BACKGROUND_NAMES):
                    return BACKGROUND_NAMES[value]
                if value in BACKGROUND_FILES:
                    return value
        except Exception:
            LOG.exception("Failed to read theme.background setting")
        return "Plain"

    def _background_tint_enabled(self):
        """True when the accent tint overlay is enabled."""
        try:
            setting = getSetting('theme.background-tint')
            if setting is not None:
                return bool(setting.getValue())
        except Exception:
            LOG.exception("Failed to read theme.background-tint setting")
        return False

    def _resolve_tint_color_hex(self):
        """Custom tint color hex string, or None to use the theme tone."""
        try:
            setting = getSetting('theme.background-tint-color')
            if setting is not None:
                value = setting.getValue()
                if isinstance(value, str) and value and value != "theme":
                    return value
        except Exception:
            LOG.exception("Failed to read theme.background-tint-color setting")
        return None

    def _resolve_theme(self):
        """Return (display_name, stylesheet_file) for the persisted setting,
        or a default based on the OS color scheme when unset/unknown."""
        try:
            setting = getSetting('theme.name')
            if setting is not None:
                value = setting.getValue()
                if isinstance(value, int) and 0 <= value < len(THEME_NAMES):
                    return THEME_NAMES[value], THEME_FILES[THEME_NAMES[value]]
                if value in THEME_FILES:
                    return value, THEME_FILES[value]
        except Exception:
            LOG.exception("Failed to read theme.name setting")
        name = "Dark Cyan" if self._is_dark_theme() else "Light Cyan"
        return name, THEME_FILES[name]

    def _apply_theme_palette(self, name):
        """Set the QPalette so palette-driven widgets (table selections,
        default widget colors, tooltips, ...) follow the theme accent too.

        Exposes CURRENT_ACCENT / CURRENT_DARK for code-painted widgets
        (the frosted dialogs), so nothing stays hardcoded blue.
        """
        global CURRENT_ACCENT, CURRENT_DARK
        accent = THEME_ACCENTS.get(name, (0, 229, 255))
        dark = name.startswith("Dark")
        CURRENT_ACCENT = accent
        CURRENT_DARK = dark

        from PySide6.QtGui import QColor, QPalette
        app = QApplication.instance()
        if app is None:
            return
        ar, ag, ab = accent

        if CURRENT_STYLE == "Ink":
            # e-paper: flat warm paper with near-black ink; no accent wash.
            # Native selection inverts to ink fill + paper text.
            window = QColor("#f2eee4")
            base = QColor("#f7f4ec")
            alt = QColor("#ece6da")
            text = QColor("#1a1a1a")
            button = QColor("#ece7db")
            placeholder = QColor("#8a8577")
        else:
            def tint(rgb, f):
                """Blend a base rgb toward the accent so even palette-driven
                widget backgrounds carry the theme hue."""
                return QColor(round(rgb[0] + (ar - rgb[0]) * f),
                              round(rgb[1] + (ag - rgb[1]) * f),
                              round(rgb[2] + (ab - rgb[2]) * f))

            if dark:
                window = tint((10, 14, 20), 0.10)
                base = tint((11, 16, 24), 0.12)
                alt = tint((17, 26, 38), 0.12)
                text = QColor("#dcefff")
                button = tint((20, 28, 40), 0.20)
                placeholder = QColor("#8ba3c7")
            else:
                window = tint((238, 242, 247), 0.10)
                base = tint((228, 234, 242), 0.12)
                alt = tint((244, 248, 252), 0.10)
                text = QColor("#16222f")
                button = tint((232, 237, 244), 0.15)
                placeholder = QColor("#5a6f88")
        if name in MONO_THEMES:
            # monochrome themes: neutral fallback text (no stray blue tones)
            text = QColor("#e6e6e6" if dark else "#1a1a1a")
            placeholder = QColor("#9a9a9a" if dark else "#6a6a6a")
        if CURRENT_STYLE == "Ink":
            highlight = QColor("#1a1a1a")
            highlighted_text = QColor("#f2eee4")
        elif name in MONO_THEMES:
            highlight = QColor(ar, ag, ab)
            highlighted_text = QColor("#f2f2f2" if not dark else "#001418")
        else:
            highlight = QColor(ar, ag, ab)
            highlighted_text = QColor("#001418")

        p = QPalette()
        p.setColor(QPalette.Window, window)
        p.setColor(QPalette.WindowText, text)
        p.setColor(QPalette.Base, base)
        p.setColor(QPalette.AlternateBase, alt)
        p.setColor(QPalette.ToolTipBase, window)
        p.setColor(QPalette.ToolTipText, text)
        p.setColor(QPalette.Text, text)
        p.setColor(QPalette.PlaceholderText, placeholder)
        p.setColor(QPalette.Button, button)
        p.setColor(QPalette.ButtonText, text)
        p.setColor(QPalette.BrightText, QColor("#ff1744"))
        p.setColor(QPalette.Highlight, highlight)
        p.setColor(QPalette.HighlightedText, highlighted_text)
        p.setColor(QPalette.Link, highlight)
        app.setPalette(p)

    def _apply_gcode_editor_theme(self):
        """Recolor the GCodeEditor chrome to match the current theme accent.

        The QSS qproperty block carries the same colors; this applies them
        programmatically so the editor matches the theme regardless of the
        startup YAML config timing.
        """
        from PySide6.QtCore import QObject
        from PySide6.QtGui import QColor
        from tnc.generate_themes import recolor_to_accent
        ar, ag, ab = CURRENT_ACCENT
        if CURRENT_STYLE == "Ink":
            # e-paper: flat warm-paper chrome with ink text; the accent stays
            # only for the line numbers and the find highlight.
            text = QColor("#1a1a1a")
            line_bg = QColor("#ece6da")
            cur_bg = QColor("#d9d2c2")
            status_bg = QColor("#ece6da")
            status_fg = QColor("#1a1a1a")
            status_border = QColor("#8a8577")
            find_hl_text = QColor("#f2eee4" if not CURRENT_DARK else "#1a1a1a")
        elif CURRENT_DARK:
            text = QColor("#dcefff")
            line_bg = QColor("#101622")
            cur_bg = QColor(round(22 + (ar - 22) * 0.22),
                            round(34 + (ag - 34) * 0.22),
                            round(54 + (ab - 54) * 0.22))
            status_bg = QColor("#141c2a")
            status_fg = QColor(round(191 + (ar - 191) * 0.5),
                               round(232 + (ag - 232) * 0.5),
                               round(255 + (ab - 255) * 0.5))
            status_border = QColor("#3c5a82")
            find_hl_text = QColor("#001418")
        else:
            text = QColor("#16222f")
            line_bg = QColor("#e0e8f2")
            cur_bg = QColor(round(228 + (ar - 228) * 0.12),
                            round(234 + (ag - 234) * 0.12),
                            round(242 + (ab - 242) * 0.12))
            status_bg = QColor("#e4ebf4")
            status_fg = QColor(round(29 + (ar - 29) * 0.5),
                               round(49 + (ag - 49) * 0.5),
                               round(72 + (ab - 72) * 0.5))
            status_border = QColor("#8fa9c8")
            find_hl_text = QColor("#001418")
        accent = QColor(ar, ag, ab)

        # Editor background/text, matching the QSS canonical colors recolored
        # to the current accent hue (Ink keeps flat paper instead).
        if CURRENT_STYLE == "Ink":
            bg_hex, text_hex = "#f7f4ec", "#1a1a1a"
        else:
            bg_base, text_rgb = ((13, 35, 51), (220, 239, 255)) \
                if CURRENT_DARK else ((221, 233, 243), (22, 34, 47))
            br, bg2, bb = recolor_to_accent(bg_base, (ar, ag, ab))
            bg_hex = "#%02x%02x%02x" % (br, bg2, bb)
            text_hex = "#%02x%02x%02x" % text_rgb

        def _swap_prop(sheet, prop, value):
            """Replace or append one CSS property, keeping the rest intact
            (qtpyvcp builds the editor sheet from YAML config)."""
            out, found = [], False
            for stmt in sheet.split(";"):
                stmt = stmt.strip()
                if not stmt:
                    continue
                if stmt.lower().startswith(prop + ":"):
                    out.append(f"{prop}: {value}")
                    found = True
                else:
                    out.append(stmt)
            if not found:
                out.append(f"{prop}: {value}")
            return "; ".join(o for o in out if o) + ";"

        all_objs = self.findChildren(QObject)
        editors = [o for o in all_objs
                   if o.metaObject().className()
                   in ('GCodeEditor', 'GcodeEditor')]
        for ed in editors:
            ed.setProperty('syntaxHighlightingEnabled', True)
            ed.setProperty('lineNumberAreaBackground', line_bg)
            ed.setProperty('lineNumberAreaColor', accent)
            ed.setProperty('currentLineHighlightEnabled', True)
            ed.setProperty('currentLineBackground', cur_bg)
            ed.setProperty('currentLineColor', text)
            ed.setProperty('findHighlightBackground', accent)
            ed.setProperty('findHighlightText', find_hl_text)
            ed.setProperty('findErrorBackground', QColor("#8c1428"))
            ed.setProperty('findErrorText', text)
            ed.setProperty('findStatusBackground', status_bg)
            ed.setProperty('findStatusText', status_fg)
            ed.setProperty('findStatusBorder', status_border)
            # The editor's background/text live in a per-widget stylesheet
            # (qtpyvcp applies YAML config there), which overrides the app
            # QSS — so swap them directly to match the theme.
            sheet = ed.styleSheet()
            sheet = _swap_prop(sheet, "background-color", bg_hex)
            sheet = _swap_prop(sheet, "color", text_hex)
            ed.setStyleSheet(sheet)

    def _apply_backplot_theme(self):
        """Recolor the VTK backplot to match the theme: the gradient
        background, the motion-type path colors and the camera-orientation
        gizmo axes. The loaded program is re-rendered so colors apply live."""
        from PySide6.QtCore import QObject, QTimer
        from PySide6.QtGui import QColor
        from tnc.generate_themes import (axis_colors,
                                         palette as _theme_palette,
                                         recolor_to_accent)

        ar, ag, ab = CURRENT_ACCENT
        if CURRENT_STYLE == "Ink":
            # e-paper: warm-paper background, ink-gray path colors and axes
            top, bottom = QColor("#f2eee4"), QColor("#ddd5c4")
            path_colors = {
                "traverse": QColor("#8a8577"),
                "feed": QColor("#1a1a1a"),
                "arcfeed": QColor("#3a3a3a"),
                "dwell": QColor("#5a554a"),
                "user": QColor("#1a1a1a"),
            }
            nav_x = QColor("#1a1a1a")
            nav_y = QColor("#5a554a")
            nav_z = QColor("#8a8577")
        else:
            if CURRENT_DARK:
                bases = ((13, 35, 51), (10, 14, 20))   # top, bottom
            else:
                bases = ((221, 233, 243), (238, 242, 247))

            top = QColor(*recolor_to_accent(bases[0], (ar, ag, ab)))
            bottom = QColor(*recolor_to_accent(bases[1], (ar, ag, ab)))
            # motion-type path colors from the consolidated accent palette
            main_hex = "#%02x%02x%02x" % (ar, ag, ab)
            if ar == ag == ab:
                pressed = "#555555" if CURRENT_DARK else "#666666"
            else:
                pressed = "#ff2bd6"
            p = _theme_palette(main_hex, pressed,
                               "dark" if CURRENT_DARK else "light")
            path_colors = {
                "traverse": QColor(p["deep"]),
                "feed": QColor(p["main"]),
                "arcfeed": QColor(p["light"]),
                "dwell": QColor(p["mid"]),
                "user": QColor(p["pressed"]),
            }
            # gizmo axes: the accent plus 120/240 degree hue rotations (or
            # distinct neutral grays for the monochrome themes) so the three
            # axes stay distinguishable and match the theme
            nav_x, nav_y, nav_z = (
                QColor(*c) for c in axis_colors((ar, ag, ab)))

        for obj in self.findChildren(QObject):
            if obj.metaObject().className() in ("VTKBackPlot", "VtkBackPlot"):
                obj.setProperty("backgroundColor", top)
                obj.setProperty("backgroundColor2", bottom)
                obj.setProperty("traverseColor", path_colors["traverse"])
                obj.setProperty("arcfeedColor", path_colors["arcfeed"])
                obj.setProperty("feedColor", path_colors["feed"])
                obj.setProperty("dwellColor", path_colors["dwell"])
                obj.setProperty("userColor", path_colors["user"])
                obj.setProperty("navHelperXAxisColor", nav_x)
                obj.setProperty("navHelperYAxisColor", nav_y)
                obj.setProperty("navHelperZAxisColor", nav_z)
                if hasattr(obj, "reapplyNavHelperConfig"):
                    obj.reapplyNavHelperConfig()
                # re-render the loaded program with the new path colors
                if (hasattr(obj, "reload_program")
                        and getattr(obj, "_last_filename", None)):
                    QTimer.singleShot(0, obj.reload_program)

    def setTheme(self, name):
        """Persist and apply a theme by display name.

        Called by the settings dialog; unknown names are ignored. The
        stylesheet swap is deferred to the next event-loop pass: re-applying
        the app stylesheet from inside a widget signal handler repolishes
        every widget while events are still being delivered, which has
        crashed the app (segfault in the VTK backplot / OpenGL stack).
        """
        if name not in THEME_FILES:
            LOG.warning("Unknown theme: %s", name)
            return
        try:
            from qtpyvcp.utilities.settings import setSetting
            setSetting('theme.name', name)
        except Exception:
            LOG.exception("Failed to save theme.name setting")
        self.reapplyStylesheet()

    def setViewStyle(self, name):
        """Persist and apply a view style by display name (deferred).

        Called by the settings dialog; unknown names are ignored. The
        stylesheet swap is deferred for the same reason as setTheme (VTK
        repolish segfault mitigation).
        """
        if name not in VIEW_STYLE_FILES:
            LOG.warning("Unknown view style: %s", name)
            return
        try:
            from qtpyvcp.utilities.settings import setSetting
            setSetting('theme.style', name)
        except Exception:
            LOG.exception("Failed to save theme.style setting")
        self.reapplyStylesheet()

    def setBackground(self, name):
        """Persist and apply a background texture by display name (deferred)."""
        if name not in BACKGROUND_FILES:
            LOG.warning("Unknown background: %s", name)
            return
        try:
            from qtpyvcp.utilities.settings import setSetting
            setSetting('theme.background', name)
        except Exception:
            LOG.exception("Failed to save theme.background setting")
        self.reapplyStylesheet()

    def setBackgroundTint(self, enabled):
        """Persist and apply the accent tint overlay (deferred)."""
        try:
            from qtpyvcp.utilities.settings import setSetting
            setSetting('theme.background-tint', bool(enabled))
        except Exception:
            LOG.exception("Failed to save theme.background-tint setting")
        self.reapplyStylesheet()

    def reapplyStylesheet(self):
        """Debounced stylesheet re-apply.

        Coalesces rapid calls (e.g. dragging an opacity slider emits many
        valueChanged signals) into a single deferred apply, and keeps the
        VTK-safe deferral used by the theme/style setters.
        """
        if getattr(self, '_style_apply_pending', False):
            return
        self._style_apply_pending = True
        QTimer.singleShot(0, self._flush_stylesheet)

    def _flush_stylesheet(self):
        self._style_apply_pending = False
        self._apply_theme_stylesheet()

    def _watch_stylesheet(self, stylesheet_path):
        """Watch a stylesheet file for changes (develop mode).

        Watches every base theme and view-style overlay file, so editing any
        of them live-reloads the combined sheet.
        """
        if self._qss_watcher is None:
            self._qss_watcher = QFileSystemWatcher(self)
            self._qss_watcher.fileChanged.connect(
                self._on_stylesheet_file_changed)
            self._watched_stylesheet_paths = set()
        self._watched_stylesheet_paths.add(stylesheet_path)
        for path in list(self._watched_stylesheet_paths):
            if os.path.isfile(path) and path not in self._qss_watcher.files():
                self._qss_watcher.addPath(path)

    def _on_stylesheet_file_changed(self, _path):
        # QFileSystemWatcher may drop paths on save/rename, so reload then re-arm.
        QTimer.singleShot(50, self._reload_watched_stylesheet)

    def _reload_watched_stylesheet(self):
        # Re-arm any dropped watch paths, then reload the combined sheet.
        paths = getattr(self, "_watched_stylesheet_paths", ())
        for path in list(paths):
            if os.path.isfile(path) and path not in self._qss_watcher.files():
                self._qss_watcher.addPath(path)
        self._apply_theme_stylesheet()


    def initUi(self):
        super().initUi()
        # Diagnostic: verify GCodeEditor YAML config was applied
        QTimer.singleShot(1000, self._diagnose_gcode_highlighting)
        # After that, force the theme's editor colors (they win at startup).
        QTimer.singleShot(1500, self._apply_gcode_editor_theme)
        QTimer.singleShot(1500, self._apply_backplot_theme)
        # Live-enable/disable the camera-orientation gizmo from the
        # backplot.show-nav-helper setting (dialog checkbox + View menu).
        try:
            from qtpyvcp.utilities.settings import connectSetting
            connectSetting('backplot.show-nav-helper',
                           self._apply_nav_helper_enabled)
        except Exception:
            LOG.exception("Failed to connect backplot.show-nav-helper setting")

    def _apply_nav_helper_enabled(self, enabled, *_args):
        """Show/hide the camera-orientation gizmo on every backplot widget
        following the ``backplot.show-nav-helper`` setting."""
        from PySide6.QtCore import QObject
        try:
            setting = getSetting('backplot.show-nav-helper')
            if setting is not None:
                enabled = bool(setting.getValue())
        except Exception:
            LOG.exception("Failed to read backplot.show-nav-helper setting")
        for obj in self.findChildren(QObject):
            if obj.metaObject().className() in ("VTKBackPlot", "VtkBackPlot"):
                obj.setProperty("navHelperEnabled", bool(enabled))
                if hasattr(obj, "reapplyNavHelperConfig"):
                    obj.reapplyNavHelperConfig()

    @Slot(QAbstractButton)
    def on_probeTabGroup_buttonClicked(self, button):
        self.probe_tab_widget.setCurrentIndex(button.property('page'))

    @Slot(QAbstractButton)
    def on_sidebarTabGroup_buttonClicked(self, button):
        self.sidebar_widget.setCurrentIndex(button.property('page'))

    # Fwd/Back buttons off the stacked widget
    def on_probe_help_next_released(self):
        lastPage = 5
        currentIndex = self.probe_help_widget.currentIndex()
        if currentIndex == lastPage:
            self.probe_help_widget.setCurrentIndex(0)
        else:
            self.probe_help_widget.setCurrentIndex(currentIndex + 1)

    def on_probe_help_prev_released(self):
        lastPage = 5
        currentIndex = self.probe_help_widget.currentIndex()
        if currentIndex == 0:
            self.probe_help_widget.setCurrentIndex(lastPage)
        else:
            self.probe_help_widget.setCurrentIndex(currentIndex - 1)

    def closeEvent(self, event):
        # Ask for confirmation before quitting when the setting is enabled.
        try:
            setting = getSetting('app.confirm-exit')
            if setting is not None and setting.getValue():
                reply = QMessageBox.question(
                    self, 'Quit TurboNC',
                    'Are you sure you want to quit TurboNC?',
                    QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
                if reply != QMessageBox.Yes:
                    event.ignore()
                    return
        except Exception:
            LOG.exception('Failed to read app.confirm-exit setting')
        super(MainWindow, self).closeEvent(event)
            
