#!/usr/bin/env python

import os

# Force qtpy to use PySide6
os.environ['QT_API'] = 'pyside6'

from PySide6.QtCore import QFileSystemWatcher, QObject, QTimer, Slot
from PySide6.QtGui import QPalette
from PySide6.QtWidgets import (QAbstractButton, QApplication, QMessageBox)

from qtpyvcp.widgets.form_widgets.main_window import VCPMainWindow
from qtpyvcp.utilities.settings import getSetting

# Setup logging
from qtpyvcp.utilities import logger

LOG = logger.getLogger("QtPyVCP." + __name__)

import resources_rc

VCP_DIR = os.path.dirname(os.path.abspath(__file__))
THEMES_DIR = "themes"


from tnc.view_styles import (BACKGROUND_FILES, BACKGROUND_NAMES,
                             VIEW_STYLE_FILES, VIEW_STYLE_NAMES,
                             render_view_style, scale_rgba_alphas,
                             tint_color, tint_overlay)

# Theme registry: display name -> qss file. The `theme.name` setting stores
# the index of the selected name in THEME_NAMES. The non-cyan variants are
# generated by generate_themes.py from the canonical dark.qss / light.qss.
# "Dark White" / "Light Black" are the monochrome black/white pair.
THEME_NAMES = [
    "Dark Cyan", "Light Cyan",
    "Dark Magenta", "Light Magenta",
    "Dark Green", "Light Green",
    "Dark Amber", "Light Amber",
    "Dark Blue", "Light Blue",
    "Dark Orange", "Light Orange",
    "Dark White", "Light Black",
]
THEME_FILES = {
    "Dark Cyan": "dark.qss",
    "Light Cyan": "light.qss",
    "Dark Magenta": "dark-magenta.qss",
    "Light Magenta": "light-magenta.qss",
    "Dark Green": "dark-green.qss",
    "Light Green": "light-green.qss",
    "Dark Amber": "dark-amber.qss",
    "Light Amber": "light-amber.qss",
    "Dark Blue": "dark-blue.qss",
    "Light Blue": "light-blue.qss",
    "Dark Orange": "dark-orange.qss",
    "Light Orange": "light-orange.qss",
    "Dark White": "dark-white.qss",
    "Light Black": "light-black.qss",
}

# Monochrome black/white pair: neutral palette text (no stray blue fallbacks).
MONO_THEMES = frozenset(("Dark White", "Light Black"))

# Accent rgb per theme (mirrors generate_themes.py ACCENTS). Used for the
# QPalette and for code-painted widgets (the frosted dialogs) so that no
# element stays hardcoded blue when a different accent is selected.
THEME_ACCENTS = {
    "Dark Cyan": (0, 229, 255), "Light Cyan": (0, 229, 255),
    "Dark Magenta": (255, 43, 214), "Light Magenta": (255, 43, 214),
    "Dark Green": (0, 255, 157), "Light Green": (0, 255, 157),
    "Dark Amber": (255, 179, 0), "Light Amber": (255, 179, 0),
    "Dark Blue": (41, 121, 255), "Light Blue": (41, 121, 255),
    "Dark Orange": (255, 115, 0), "Light Orange": (255, 115, 0),
    "Dark White": (242, 242, 242), "Light Black": (26, 26, 26),
}

# Updated on every theme apply; read by code-painted widgets (dialogs).
CURRENT_ACCENT = (0, 229, 255)
CURRENT_DARK = True
# Active view style (Neon, Flat, ..., Ink); read by code-painted widgets so
# the e-paper Ink style gets paper fills instead of accent-tinted glass.
CURRENT_STYLE = "Neon"


def glass_fill():
    """Top/bottom QColor pair for the frosted dialog fill, tinted toward the
    current accent so the dialog glass matches the selected theme. The fill
    alpha follows the panel-opacity setting. The Ink view style switches to
    near-opaque warm paper so the dialogs match the e-paper look."""
    from PySide6.QtGui import QColor
    factor = _opacity_setting('theme.panel-opacity', 100) / 100.0
    if CURRENT_STYLE == "Ink":
        alpha = round(252 * factor)
        return (QColor(247, 244, 236, alpha),
                QColor(236, 230, 218, alpha))
    ar, ag, ab = CURRENT_ACCENT
    alpha = round(228 * factor)
    top = QColor(round(22 + (ar - 22) * 0.22),
                 round(34 + (ag - 34) * 0.22),
                 round(54 + (ab - 54) * 0.22), alpha)
    bottom = QColor(round(13 + (ar - 13) * 0.10),
                    round(20 + (ag - 20) * 0.10),
                    round(34 + (ab - 34) * 0.10), alpha)
    return top, bottom


def glass_border():
    """Border QColor for the glass dialogs.

    The Ink style draws a flat ink-gray border instead of the neon accent so
    the dialogs match the e-paper look."""
    from PySide6.QtGui import QColor
    if CURRENT_STYLE == "Ink":
        return QColor(58, 58, 58, 220)
    ar, ag, ab = CURRENT_ACCENT
    return QColor(ar, ag, ab, 150)


def glass_glow():
    """(start, end) QColor pair for the dialogs' top-left soft glow.

    Ink uses a faint warm-paper shadow so no neon glow bleeds into the
    e-paper look; other styles keep the subtle accent glow."""
    from PySide6.QtGui import QColor
    if CURRENT_STYLE == "Ink":
        return QColor(120, 108, 88, 28), QColor(120, 108, 88, 0)
    ar, ag, ab = CURRENT_ACCENT
    return QColor(ar, ag, ab, 40), QColor(ar, ag, ab, 0)


def _opacity_setting(setting_id, default=100):
    """Int 0..255 from a persisted opacity setting (or default)."""
    try:
        setting = getSetting(setting_id)
        if setting is not None:
            return max(0, min(255, int(setting.getValue())))
    except Exception:
        pass
    return default


def glass_path(rect, cut=12):
    """QPainterPath with chamfered (cut) corners for the glass dialogs."""
    from PySide6.QtGui import QPainterPath
    path = QPainterPath()
    x0, y0, x1, y1 = rect.left(), rect.top(), rect.right(), rect.bottom()
    path.moveTo(x0 + cut, y0)
    path.lineTo(x1 - cut, y0)
    path.lineTo(x1, y0 + cut)
    path.lineTo(x1, y1 - cut)
    path.lineTo(x1 - cut, y1)
    path.lineTo(x0 + cut, y1)
    path.lineTo(x0, y1 - cut)
    path.lineTo(x0, y0 + cut)
    path.closeSubpath()
    return path

class MainWindow(VCPMainWindow):
    def __init__(self, *args, **kwargs):
        opts = kwargs.get('opts')
        self._develop_mode = bool(getattr(opts, 'develop', False))
        self._qss_watcher = None

        super(MainWindow, self).__init__(*args, **kwargs)

        self._connect_theme_tracking()
        self._apply_theme_stylesheet()

        self.initUi()

        # self.plot.camera.Zoom(0.002)
        # self.plot.setViewMachine()

    def _is_dark_theme(self):
        app = QApplication.instance()
        if app is None:
            return False
        palette = app.palette()
        window_lightness = palette.color(QPalette.Window).lightness()
        base_lightness = palette.color(QPalette.Base).lightness()
        return ((window_lightness + base_lightness) / 2) < 128

    def _diagnose_gcode_highlighting(self):
        """Ensure GCodeEditor syntax highlighting is properly configured.

        The framework applies YAML config via _apply_gcode_editor_yaml_config,
        but a timing issue can leave properties reset to their .ui file defaults
        on some editors. This runs late as a safety net, reading the same YAML
        config that the framework already loaded into qtpyvcp.CONFIG.
        """
        from PySide6.QtCore import QObject
        from PySide6.QtGui import QColor
        import qtpyvcp

        all_objs = self.findChildren(QObject)
        gcode_editors = [o for o in all_objs
                         if o.metaObject().className() in ('GCodeEditor', 'GcodeEditor')]

        if not gcode_editors:
            LOG.warning("No GCodeEditor widgets found")
            return

        # Read token→color map from YAML (same source as the framework uses)
        syntax_config = qtpyvcp.CONFIG.get('gcode_syntax_profile', {})
        token_color_map = {}
        for style in syntax_config.get('syntax_styles', []):
            color = style.get('color')
            if not color:
                continue
            qcolor = QColor(color)
            if not qcolor.isValid():
                continue
            for token in style.get('tokens', []):
                token_color_map[token] = qcolor

        # Read current-line style from YAML
        style_defaults = qtpyvcp.CONFIG.get('gcode_editor_style_defaults', {})
        cl_enabled = style_defaults.get('current_line_highlight_enabled', True)
        cl_bg = style_defaults.get('current_line_background', '#3a3a5a')
        cl_fg = style_defaults.get('current_line_color', '#d4d4d4')

        for editor in gcode_editors:
            name = editor.objectName()

            if token_color_map and hasattr(editor, 'setTokenColorMap'):
                se_enabled = editor.property('syntaxHighlightingEnabled')
                if not se_enabled:
                    LOG.warning("Editor '%s': syntaxHighlightingEnabled was False, forcing to True", name)
                editor.setTokenColorMap(token_color_map)
                editor.setProperty('syntaxHighlightingEnabled', True)
                LOG.info("Editor '%s': highlighting applied (%d token types)",
                         name, len(token_color_map))

            # Force-enable current-line highlight (same timing issue as above)
            cur_enabled = editor.property('currentLineHighlightEnabled')
            if not cur_enabled:
                LOG.warning("Editor '%s': currentLineHighlightEnabled was False, forcing to True", name)
            editor.setProperty('currentLineHighlightEnabled', bool(cl_enabled))
            editor.setProperty('currentLineBackground', QColor(cl_bg))
            editor.setProperty('currentLineColor', QColor(cl_fg))

    def _connect_theme_tracking(self):
        app = QApplication.instance()
        if app is None:
            return
        palette_changed = getattr(app, 'paletteChanged', None)
        if palette_changed is not None:
            try:
                palette_changed.connect(self._on_palette_changed)
            except Exception:
                LOG.exception("Failed to connect paletteChanged signal")

    def _on_palette_changed(self, *_args):
        QTimer.singleShot(0, self._apply_theme_stylesheet)

    def _apply_theme_stylesheet(self):
        global CURRENT_STYLE
        name, stylesheet_file = self._resolve_theme()
        style_name = self._resolve_style()
        CURRENT_STYLE = style_name
        app = QApplication.instance()
        if app is None:
            return
        try:
            # Palette first: exposes CURRENT_ACCENT / CURRENT_DARK (and
            # CURRENT_STYLE), which the view-style overlay renderer (and
            # code-painted widgets) use.
            self._apply_theme_palette(name)
            stylesheet_path = os.path.join(VCP_DIR, THEMES_DIR,
                                           stylesheet_file)
            with open(stylesheet_path, 'r', encoding='utf-8') as style_file:
                base_qss = style_file.read()
            style_path = os.path.join(VCP_DIR, THEMES_DIR,
                                      VIEW_STYLE_FILES[style_name])
            with open(style_path, 'r', encoding='utf-8') as style_file:
                overlay_qss = style_file.read()
            extra_tokens = None
            if style_name == "Ink":
                # absolute path to the paper checkmark the Ink checkbox uses
                extra_tokens = {"check_icon": os.path.join(
                    VCP_DIR, THEMES_DIR, "styles", "ink-check.svg")}
            overlay_qss = render_view_style(overlay_qss, CURRENT_ACCENT,
                                            CURRENT_DARK, extra_tokens)
            # background texture (optional) appended last, stretched to fill
            bg_rule = ""
            bg_file = BACKGROUND_FILES.get(self._resolve_background())
            if bg_file:
                bg_path = os.path.join(VCP_DIR, THEMES_DIR, bg_file)
                bg_rule = ("\n/* background texture */\nQMainWindow {\n"
                           "    border-image: url(%s) 0 0 0 0 stretch "
                           "stretch;\n}\n" % bg_path)
            # optional accent tint: a translucent wash on the central widget,
            # overlaying whatever background (texture or plain) is behind it.
            # Its alpha comes from the tint-opacity setting, untouched by the
            # panel-opacity scaling below.
            if self._background_tint_enabled():
                tr, tg, tb, _ta = tint_overlay(
                    CURRENT_ACCENT, CURRENT_DARK,
                    self._resolve_tint_color_hex())
                tint_alpha = _opacity_setting(
                    'theme.background-tint-opacity', 40)
                bg_rule += ("\n/* accent tint overlay */\n"
                            "QWidget#centralwidget {\n"
                            "    background: rgba(%d, %d, %d, %d);\n}\n"
                            % (tr, tg, tb, tint_alpha))
            # panel opacity: scale every translucent rgba fill in the sheet
            sheet = base_qss + "\n" + overlay_qss
            panel_opacity = _opacity_setting('theme.panel-opacity', 100)
            if panel_opacity < 100:
                sheet = scale_rgba_alphas(sheet, panel_opacity / 100.0)
            app.setStyleSheet(sheet + bg_rule)
            self._apply_gcode_editor_theme()
            self._apply_backplot_theme()
            if self._develop_mode:
                self._watch_stylesheet(stylesheet_path)
                self._watch_stylesheet(style_path)
                if bg_file:
                    self._watch_stylesheet(os.path.join(VCP_DIR, THEMES_DIR,
                                                        bg_file))
        except Exception:
            LOG.exception("Failed to load theme stylesheet: %s",
                          stylesheet_path)

    def _resolve_style(self):
        """Return the view-style display name for the persisted setting."""
        try:
            setting = getSetting('theme.style')
            if setting is not None:
                value = setting.getValue()
                if isinstance(value, int) and 0 <= value < len(VIEW_STYLE_NAMES):
                    return VIEW_STYLE_NAMES[value]
                if value in VIEW_STYLE_FILES:
                    return value
        except Exception:
            LOG.exception("Failed to read theme.style setting")
        return "Neon"

    def _resolve_background(self):
        """Return the background texture display name for the setting."""
        try:
            setting = getSetting('theme.background')
            if setting is not None:
                value = setting.getValue()
                if isinstance(value, int) and 0 <= value < len(BACKGROUND_NAMES):
                    return BACKGROUND_NAMES[value]
                if value in BACKGROUND_FILES:
                    return value
        except Exception:
            LOG.exception("Failed to read theme.background setting")
        return "Plain"

    def _background_tint_enabled(self):
        """True when the accent tint overlay is enabled."""
        try:
            setting = getSetting('theme.background-tint')
            if setting is not None:
                return bool(setting.getValue())
        except Exception:
            LOG.exception("Failed to read theme.background-tint setting")
        return False

    def _resolve_tint_color_hex(self):
        """Custom tint color hex string, or None to use the theme tone."""
        try:
            setting = getSetting('theme.background-tint-color')
            if setting is not None:
                value = setting.getValue()
                if isinstance(value, str) and value and value != "theme":
                    return value
        except Exception:
            LOG.exception("Failed to read theme.background-tint-color setting")
        return None

    def _resolve_theme(self):
        """Return (display_name, stylesheet_file) for the persisted setting,
        or a default based on the OS color scheme when unset/unknown."""
        try:
            setting = getSetting('theme.name')
            if setting is not None:
                value = setting.getValue()
                if isinstance(value, int) and 0 <= value < len(THEME_NAMES):
                    return THEME_NAMES[value], THEME_FILES[THEME_NAMES[value]]
                if value in THEME_FILES:
                    return value, THEME_FILES[value]
        except Exception:
            LOG.exception("Failed to read theme.name setting")
        name = "Dark Cyan" if self._is_dark_theme() else "Light Cyan"
        return name, THEME_FILES[name]

    def _apply_theme_palette(self, name):
        """Set the QPalette so palette-driven widgets (table selections,
        default widget colors, tooltips, ...) follow the theme accent too.

        Exposes CURRENT_ACCENT / CURRENT_DARK for code-painted widgets
        (the frosted dialogs), so nothing stays hardcoded blue.
        """
        global CURRENT_ACCENT, CURRENT_DARK
        accent = THEME_ACCENTS.get(name, (0, 229, 255))
        dark = name.startswith("Dark")
        CURRENT_ACCENT = accent
        CURRENT_DARK = dark

        from PySide6.QtGui import QColor, QPalette
        app = QApplication.instance()
        if app is None:
            return
        ar, ag, ab = accent

        if CURRENT_STYLE == "Ink":
            # e-paper: flat warm paper with near-black ink; no accent wash.
            # Native selection inverts to ink fill + paper text.
            window = QColor("#f2eee4")
            base = QColor("#f7f4ec")
            alt = QColor("#ece6da")
            text = QColor("#1a1a1a")
            button = QColor("#ece7db")
            placeholder = QColor("#8a8577")
        else:
            def tint(rgb, f):
                """Blend a base rgb toward the accent so even palette-driven
                widget backgrounds carry the theme hue."""
                return QColor(round(rgb[0] + (ar - rgb[0]) * f),
                              round(rgb[1] + (ag - rgb[1]) * f),
                              round(rgb[2] + (ab - rgb[2]) * f))

            if dark:
                window = tint((10, 14, 20), 0.10)
                base = tint((11, 16, 24), 0.12)
                alt = tint((17, 26, 38), 0.12)
                text = QColor("#dcefff")
                button = tint((20, 28, 40), 0.20)
                placeholder = QColor("#8ba3c7")
            else:
                window = tint((238, 242, 247), 0.10)
                base = tint((228, 234, 242), 0.12)
                alt = tint((244, 248, 252), 0.10)
                text = QColor("#16222f")
                button = tint((232, 237, 244), 0.15)
                placeholder = QColor("#5a6f88")
        if name in MONO_THEMES:
            # monochrome themes: neutral fallback text (no stray blue tones)
            text = QColor("#e6e6e6" if dark else "#1a1a1a")
            placeholder = QColor("#9a9a9a" if dark else "#6a6a6a")
        if CURRENT_STYLE == "Ink":
            highlight = QColor("#1a1a1a")
            highlighted_text = QColor("#f2eee4")
        elif name in MONO_THEMES:
            highlight = QColor(ar, ag, ab)
            highlighted_text = QColor("#f2f2f2" if not dark else "#001418")
        else:
            highlight = QColor(ar, ag, ab)
            highlighted_text = QColor("#001418")

        p = QPalette()
        p.setColor(QPalette.Window, window)
        p.setColor(QPalette.WindowText, text)
        p.setColor(QPalette.Base, base)
        p.setColor(QPalette.AlternateBase, alt)
        p.setColor(QPalette.ToolTipBase, window)
        p.setColor(QPalette.ToolTipText, text)
        p.setColor(QPalette.Text, text)
        p.setColor(QPalette.PlaceholderText, placeholder)
        p.setColor(QPalette.Button, button)
        p.setColor(QPalette.ButtonText, text)
        p.setColor(QPalette.BrightText, QColor("#ff1744"))
        p.setColor(QPalette.Highlight, highlight)
        p.setColor(QPalette.HighlightedText, highlighted_text)
        p.setColor(QPalette.Link, highlight)
        app.setPalette(p)

    def _apply_gcode_editor_theme(self):
        """Recolor the GCodeEditor chrome to match the current theme accent.

        The QSS qproperty block carries the same colors; this applies them
        programmatically so the editor matches the theme regardless of the
        startup YAML config timing.
        """
        from PySide6.QtCore import QObject
        from PySide6.QtGui import QColor
        from tnc.generate_themes import recolor_to_accent
        ar, ag, ab = CURRENT_ACCENT
        if CURRENT_STYLE == "Ink":
            # e-paper: flat warm-paper chrome with ink text; the accent stays
            # only for the line numbers and the find highlight.
            text = QColor("#1a1a1a")
            line_bg = QColor("#ece6da")
            cur_bg = QColor("#d9d2c2")
            status_bg = QColor("#ece6da")
            status_fg = QColor("#1a1a1a")
            status_border = QColor("#8a8577")
            find_hl_text = QColor("#f2eee4" if not CURRENT_DARK else "#1a1a1a")
        elif CURRENT_DARK:
            text = QColor("#dcefff")
            line_bg = QColor("#101622")
            cur_bg = QColor(round(22 + (ar - 22) * 0.22),
                            round(34 + (ag - 34) * 0.22),
                            round(54 + (ab - 54) * 0.22))
            status_bg = QColor("#141c2a")
            status_fg = QColor(round(191 + (ar - 191) * 0.5),
                               round(232 + (ag - 232) * 0.5),
                               round(255 + (ab - 255) * 0.5))
            status_border = QColor("#3c5a82")
            find_hl_text = QColor("#001418")
        else:
            text = QColor("#16222f")
            line_bg = QColor("#e0e8f2")
            cur_bg = QColor(round(228 + (ar - 228) * 0.12),
                            round(234 + (ag - 234) * 0.12),
                            round(242 + (ab - 242) * 0.12))
            status_bg = QColor("#e4ebf4")
            status_fg = QColor(round(29 + (ar - 29) * 0.5),
                               round(49 + (ag - 49) * 0.5),
                               round(72 + (ab - 72) * 0.5))
            status_border = QColor("#8fa9c8")
            find_hl_text = QColor("#001418")
        accent = QColor(ar, ag, ab)

        # Editor background/text, matching the QSS canonical colors recolored
        # to the current accent hue (Ink keeps flat paper instead).
        if CURRENT_STYLE == "Ink":
            bg_hex, text_hex = "#f7f4ec", "#1a1a1a"
        else:
            bg_base, text_rgb = ((13, 35, 51), (220, 239, 255)) \
                if CURRENT_DARK else ((221, 233, 243), (22, 34, 47))
            br, bg2, bb = recolor_to_accent(bg_base, (ar, ag, ab))
            bg_hex = "#%02x%02x%02x" % (br, bg2, bb)
            text_hex = "#%02x%02x%02x" % text_rgb

        def _swap_prop(sheet, prop, value):
            """Replace or append one CSS property, keeping the rest intact
            (qtpyvcp builds the editor sheet from YAML config)."""
            out, found = [], False
            for stmt in sheet.split(";"):
                stmt = stmt.strip()
                if not stmt:
                    continue
                if stmt.lower().startswith(prop + ":"):
                    out.append(f"{prop}: {value}")
                    found = True
                else:
                    out.append(stmt)
            if not found:
                out.append(f"{prop}: {value}")
            return "; ".join(o for o in out if o) + ";"

        all_objs = self.findChildren(QObject)
        editors = [o for o in all_objs
                   if o.metaObject().className()
                   in ('GCodeEditor', 'GcodeEditor')]
        for ed in editors:
            ed.setProperty('syntaxHighlightingEnabled', True)
            ed.setProperty('lineNumberAreaBackground', line_bg)
            ed.setProperty('lineNumberAreaColor', accent)
            ed.setProperty('currentLineHighlightEnabled', True)
            ed.setProperty('currentLineBackground', cur_bg)
            ed.setProperty('currentLineColor', text)
            ed.setProperty('findHighlightBackground', accent)
            ed.setProperty('findHighlightText', find_hl_text)
            ed.setProperty('findErrorBackground', QColor("#8c1428"))
            ed.setProperty('findErrorText', text)
            ed.setProperty('findStatusBackground', status_bg)
            ed.setProperty('findStatusText', status_fg)
            ed.setProperty('findStatusBorder', status_border)
            # The editor's background/text live in a per-widget stylesheet
            # (qtpyvcp applies YAML config there), which overrides the app
            # QSS — so swap them directly to match the theme.
            sheet = ed.styleSheet()
            sheet = _swap_prop(sheet, "background-color", bg_hex)
            sheet = _swap_prop(sheet, "color", text_hex)
            ed.setStyleSheet(sheet)

    def _apply_backplot_theme(self):
        """Recolor the VTK backplot to match the theme: the gradient
        background, the motion-type path colors and the camera-orientation
        gizmo axes. The loaded program is re-rendered so colors apply live."""
        from PySide6.QtCore import QObject, QTimer
        from PySide6.QtGui import QColor
        from tnc.generate_themes import (axis_colors,
                                         palette as _theme_palette,
                                         recolor_to_accent)

        ar, ag, ab = CURRENT_ACCENT
        if CURRENT_STYLE == "Ink":
            # e-paper: warm-paper background, ink-gray path colors and axes
            top, bottom = QColor("#f2eee4"), QColor("#ddd5c4")
            path_colors = {
                "traverse": QColor("#8a8577"),
                "feed": QColor("#1a1a1a"),
                "arcfeed": QColor("#3a3a3a"),
                "dwell": QColor("#5a554a"),
                "user": QColor("#1a1a1a"),
            }
            nav_x = QColor("#1a1a1a")
            nav_y = QColor("#5a554a")
            nav_z = QColor("#8a8577")
        else:
            if CURRENT_DARK:
                bases = ((13, 35, 51), (10, 14, 20))   # top, bottom
            else:
                bases = ((221, 233, 243), (238, 242, 247))

            top = QColor(*recolor_to_accent(bases[0], (ar, ag, ab)))
            bottom = QColor(*recolor_to_accent(bases[1], (ar, ag, ab)))
            # motion-type path colors from the consolidated accent palette
            main_hex = "#%02x%02x%02x" % (ar, ag, ab)
            if ar == ag == ab:
                pressed = "#555555" if CURRENT_DARK else "#666666"
            else:
                pressed = "#ff2bd6"
            p = _theme_palette(main_hex, pressed,
                               "dark" if CURRENT_DARK else "light")
            path_colors = {
                "traverse": QColor(p["deep"]),
                "feed": QColor(p["main"]),
                "arcfeed": QColor(p["light"]),
                "dwell": QColor(p["mid"]),
                "user": QColor(p["pressed"]),
            }
            # gizmo axes: the accent plus 120/240 degree hue rotations (or
            # distinct neutral grays for the monochrome themes) so the three
            # axes stay distinguishable and match the theme
            nav_x, nav_y, nav_z = (
                QColor(*c) for c in axis_colors((ar, ag, ab)))

        for obj in self.findChildren(QObject):
            if obj.metaObject().className() in ("VTKBackPlot", "VtkBackPlot"):
                obj.setProperty("backgroundColor", top)
                obj.setProperty("backgroundColor2", bottom)
                obj.setProperty("traverseColor", path_colors["traverse"])
                obj.setProperty("arcfeedColor", path_colors["arcfeed"])
                obj.setProperty("feedColor", path_colors["feed"])
                obj.setProperty("dwellColor", path_colors["dwell"])
                obj.setProperty("userColor", path_colors["user"])
                obj.setProperty("navHelperXAxisColor", nav_x)
                obj.setProperty("navHelperYAxisColor", nav_y)
                obj.setProperty("navHelperZAxisColor", nav_z)
                if hasattr(obj, "reapplyNavHelperConfig"):
                    obj.reapplyNavHelperConfig()
                # re-render the loaded program with the new path colors
                if (hasattr(obj, "reload_program")
                        and getattr(obj, "_last_filename", None)):
                    QTimer.singleShot(0, obj.reload_program)

    def setTheme(self, name):
        """Persist and apply a theme by display name.

        Called by the settings dialog; unknown names are ignored. The
        stylesheet swap is deferred to the next event-loop pass: re-applying
        the app stylesheet from inside a widget signal handler repolishes
        every widget while events are still being delivered, which has
        crashed the app (segfault in the VTK backplot / OpenGL stack).
        """
        if name not in THEME_FILES:
            LOG.warning("Unknown theme: %s", name)
            return
        try:
            from qtpyvcp.utilities.settings import setSetting
            setSetting('theme.name', name)
        except Exception:
            LOG.exception("Failed to save theme.name setting")
        self.reapplyStylesheet()

    def setViewStyle(self, name):
        """Persist and apply a view style by display name (deferred).

        Called by the settings dialog; unknown names are ignored. The
        stylesheet swap is deferred for the same reason as setTheme (VTK
        repolish segfault mitigation).
        """
        if name not in VIEW_STYLE_FILES:
            LOG.warning("Unknown view style: %s", name)
            return
        try:
            from qtpyvcp.utilities.settings import setSetting
            setSetting('theme.style', name)
        except Exception:
            LOG.exception("Failed to save theme.style setting")
        self.reapplyStylesheet()

    def setBackground(self, name):
        """Persist and apply a background texture by display name (deferred)."""
        if name not in BACKGROUND_FILES:
            LOG.warning("Unknown background: %s", name)
            return
        try:
            from qtpyvcp.utilities.settings import setSetting
            setSetting('theme.background', name)
        except Exception:
            LOG.exception("Failed to save theme.background setting")
        self.reapplyStylesheet()

    def setBackgroundTint(self, enabled):
        """Persist and apply the accent tint overlay (deferred)."""
        try:
            from qtpyvcp.utilities.settings import setSetting
            setSetting('theme.background-tint', bool(enabled))
        except Exception:
            LOG.exception("Failed to save theme.background-tint setting")
        self.reapplyStylesheet()

    def reapplyStylesheet(self):
        """Debounced stylesheet re-apply.

        Coalesces rapid calls (e.g. dragging an opacity slider emits many
        valueChanged signals) into a single deferred apply, and keeps the
        VTK-safe deferral used by the theme/style setters.
        """
        if getattr(self, '_style_apply_pending', False):
            return
        self._style_apply_pending = True
        QTimer.singleShot(0, self._flush_stylesheet)

    def _flush_stylesheet(self):
        self._style_apply_pending = False
        self._apply_theme_stylesheet()

    def _watch_stylesheet(self, stylesheet_path):
        """Watch a stylesheet file for changes (develop mode).

        Watches every base theme and view-style overlay file, so editing any
        of them live-reloads the combined sheet.
        """
        if self._qss_watcher is None:
            self._qss_watcher = QFileSystemWatcher(self)
            self._qss_watcher.fileChanged.connect(
                self._on_stylesheet_file_changed)
            self._watched_stylesheet_paths = set()
        self._watched_stylesheet_paths.add(stylesheet_path)
        for path in list(self._watched_stylesheet_paths):
            if os.path.isfile(path) and path not in self._qss_watcher.files():
                self._qss_watcher.addPath(path)

    def _on_stylesheet_file_changed(self, _path):
        # QFileSystemWatcher may drop paths on save/rename, so reload then re-arm.
        QTimer.singleShot(50, self._reload_watched_stylesheet)

    def _reload_watched_stylesheet(self):
        # Re-arm any dropped watch paths, then reload the combined sheet.
        paths = getattr(self, "_watched_stylesheet_paths", ())
        for path in list(paths):
            if os.path.isfile(path) and path not in self._qss_watcher.files():
                self._qss_watcher.addPath(path)
        self._apply_theme_stylesheet()


    def initUi(self):
        super().initUi()
        # Diagnostic: verify GCodeEditor YAML config was applied
        QTimer.singleShot(1000, self._diagnose_gcode_highlighting)
        # After that, force the theme's editor colors (they win at startup).
        QTimer.singleShot(1500, self._apply_gcode_editor_theme)
        QTimer.singleShot(1500, self._apply_backplot_theme)
        # Live-enable/disable the camera-orientation gizmo from the
        # backplot.show-nav-helper setting (dialog checkbox + View menu).
        try:
            from qtpyvcp.utilities.settings import connectSetting
            connectSetting('backplot.show-nav-helper',
                           self._apply_nav_helper_enabled)
        except Exception:
            LOG.exception("Failed to connect backplot.show-nav-helper setting")
        self._wire_joint_jog_buttons()
        self._wire_cell_buttons()
        self._wire_lcnc_indicators()
        self._wire_jog_controls()
        self._build_set_to_zero_panel()
        self._wire_dro_offset_buttons()
        self._wire_tool_change_controls()

    # ------------------------------------------------------------------
    # Tools tab: "Tool Change" groupbox (change tool + optional G43 H TLO)
    # ------------------------------------------------------------------
    def _wire_tool_change_controls(self):
        """Wire the Program tab "Tool Change" groupbox.

        CHANGE TOOL issues ``T<n> M6`` and, when the TLO checkbox is ticked,
        appends ``G43 H<n>`` to enable tool length compensation.
        """
        from PySide6.QtWidgets import QCheckBox, QPushButton, QSpinBox

        self._tool_number_entry = self.findChild(QSpinBox, 'tool_number_entry')
        self._enable_tlo_checkbox = self.findChild(QCheckBox, 'enable_tlo_checkbox')
        change_btn = self.findChild(QPushButton, 'change_tool_button')
        if change_btn is None:
            LOG.info("Tool Change groupbox not found in window.ui")
            return
        change_btn.clicked.connect(self._change_tool)

        # seed with the tool currently in the spindle and keep it in sync
        self._sync_tool_number()
        try:
            from qtpyvcp.plugins import getPlugin
            getPlugin('status').tool_in_spindle.notify(
                lambda _v=None: self._sync_tool_number())
        except Exception:
            LOG.debug("tool_in_spindle channel unavailable; "
                      "TOOL CHANGE spinbox will not auto-sync")

    def _sync_tool_number(self):
        w = getattr(self, '_tool_number_entry', None)
        if w is None or w.hasFocus():
            return
        st = self._lc_stat()
        if st is None:
            return
        try:
            st.poll()
            n = int(st.tool_in_spindle)
        except Exception:
            return
        if n > 0 and w.value() != n:
            w.setValue(n)

    def _tool_number(self):
        w = getattr(self, '_tool_number_entry', None)
        try:
            return int(w.value())
        except Exception:
            return 0

    def _change_tool(self):
        from qtpyvcp.actions.machine_actions import issue_mdi
        n = self._tool_number()
        if n <= 0:
            return
        cmd = "T%d M6" % n
        cb = getattr(self, '_enable_tlo_checkbox', None)
        if cb is not None and cb.isChecked():
            cmd += " G43 H%d" % n
        issue_mdi(cmd)
        LOG.info("tool change: %s", cmd)

    # ------------------------------------------------------------------
    # DRO: per-axis "set offset" button before each axis letter
    # ------------------------------------------------------------------
    def _wire_dro_offset_buttons(self):
        """Connect the per-axis "set offset" buttons declared in window.ui.

        Each is named ``dro_offset_<rel|abs>_<AXIS>`` and sits immediately
        before the axis letter in the Relative (``tab_8``) and Absolute
        (``tab_7``) DRO rows.  Clicking it opens
        :class:`tnc.dialogs.axis_offset.AxisOffsetDialog` for that axis.
        """
        from PySide6.QtWidgets import QPushButton

        count = 0
        for btn in self.findChildren(QPushButton):
            name = btn.objectName()
            if not name.startswith("dro_offset_"):
                continue
            axis = name.rsplit("_", 1)[-1].upper()
            if len(axis) != 1 or axis not in "XYZABCUVW":
                continue
            btn.clicked.connect(
                lambda _=False, a=axis: self._open_axis_offset_dialog(a))
            count += 1
        LOG.info("DRO offset buttons wired: %d", count)

    def _open_axis_offset_dialog(self, axis):
        try:
            from tnc.dialogs.axis_offset import AxisOffsetDialog
        except Exception:
            LOG.exception("could not import AxisOffsetDialog")
            return
        dlg = AxisOffsetDialog(axis, parent=self)
        dlg.open()

    # ------------------------------------------------------------------
    # Offsets tab: "SET TO ZERO" per-axis touch-off panel
    # ------------------------------------------------------------------
    @staticmethod
    def _lc_stat():
        try:
            from qtpyvcp.plugins import getPlugin
            return getPlugin('status').stat
        except Exception:
            try:
                from qtpyvcp.plugins.status import STAT
                return STAT
            except Exception:
                return None

    def _build_set_to_zero_panel(self):
        """Fill the Offsets tab's frame_32 placeholder with one row per axis.

        Each row shows WC current position, machine coords, WC offset,
        G52/G92 offset and tool offset, plus a ZERO button that touch-offs
        that axis of the active WCS at the current position
        (``G10 L20 P<wcs> <axis>0``).
        """
        from PySide6.QtWidgets import (QGridLayout, QLabel, QPushButton,
                                       QVBoxLayout)
        from PySide6.QtGui import QFont
        from qtpyvcp.utilities.info import Info

        frame = self.findChild(QObject, 'frame_32')
        if frame is None:
            LOG.warning("Offsets tab: frame_32 placeholder not found; "
                        "SET TO ZERO panel not built")
            return

        base = frame.layout()
        if base is None:
            base = QVBoxLayout(frame)
        else:
            while base.count():
                item = base.takeAt(0)
                w = item.widget()
                if w is not None:
                    w.deleteLater()

        try:
            self._stz_axes = list(Info().getCoordinates())
        except Exception:
            self._stz_axes = ['x', 'y', 'z', 'a', 'b', 'c']

        grid = QGridLayout()
        base.addLayout(grid)
        grid.setContentsMargins(2, 2, 2, 2)
        grid.setSpacing(3)
        head_font = QFont("3270 Semi-Condensed", 10)
        cell_font = QFont("Monospace", 10)
        heads = ["SET TO ZERO", "AXIS", "WC CURRENT", "MACHINE",
                 "WC OFFSET", "G52/G92", "TOOL OFFSET"]
        for c, h in enumerate(heads):
            lbl = QLabel(h)
            lbl.setFont(head_font)
            grid.addWidget(lbl, 0, c)

        self._stz_cells = {}
        for r, ax in enumerate(self._stz_axes, start=1):
            btn = QPushButton("ZERO")
            btn.setFixedWidth(52)
            btn.clicked.connect(lambda _=False, a=ax: self._set_axis_zero(a))
            grid.addWidget(btn, r, 0)
            al = QLabel(ax.upper())
            al.setFont(head_font)
            grid.addWidget(al, r, 1)
            cells = []
            for c in range(2, 7):
                lbl = QLabel("0.0000")
                lbl.setFont(cell_font)
                grid.addWidget(lbl, r, c)
                cells.append(lbl)
            self._stz_cells[ax] = cells

        if not hasattr(self, '_stz_timer'):
            self._stz_timer = QTimer(self)
            self._stz_timer.timeout.connect(self._update_set_to_zero_panel)
            self._stz_timer.start(150)
        self._update_set_to_zero_panel()

    def _set_axis_zero(self, axis):
        """Touch off ``axis`` of the active WCS at the current position."""
        from qtpyvcp.actions.machine_actions import issue_mdi
        st = self._lc_stat()
        try:
            st.poll()
            wcs = int(st.g5x_index)
        except Exception:
            wcs = 1
        wcs = max(1, min(9, wcs))
        issue_mdi("G10 L20 P%d %s0" % (wcs, axis.upper()))

    def _update_set_to_zero_panel(self):
        cells = getattr(self, '_stz_cells', None)
        if not cells:
            return
        st = self._lc_stat()
        if st is None:
            return
        try:
            st.poll()
            machine = list(st.actual_position)
            g5x = list(st.g5x_offset)
            g92 = list(st.g92_offset)
            tool = list(st.tool_offset)
        except Exception:
            return
        for i, ax in enumerate(self._stz_axes):
            if ax not in cells or i >= len(machine):
                continue
            wc = machine[i] - g5x[i] - g92[i] - tool[i]
            for lbl, v in zip(cells[ax],
                              (wc, machine[i], g5x[i], g92[i], tool[i])):
                lbl.setText("%.4f" % v)

    # ------------------------------------------------------------------
    # Cells tab: kinematics mode + subroutine call buttons
    # ------------------------------------------------------------------
    def _wire_cell_buttons(self):
        """Set up the Cells tab's live kinematics-mode indicator.

        The cell SubCallButtons and kinematics MDIButtons are declared in
        window.ui as native qtpyvcp widgets (SubCallButton / MDIButton) which
        handle their own MDI calls, mode switching and enable/disable - no
        manual wiring needed. We just poll the kinematics type to keep the
        status label updated.
        """
        self._kins_timer = QTimer(self)
        self._kins_timer.setInterval(500)
        self._kins_timer.timeout.connect(self._refresh_kins_mode)
        self._kins_timer.start()
        self._refresh_kins_mode()

    def _refresh_kins_mode(self):
        """Reflect the live kinematics type on the mode label.

        Prefers ``motion.kins-type`` (the OUT pin G12.1/G13.1 update), falling
        back to the deprecated ``motion.switchkins-type`` input pin for older
        configurations that still drive the switch through HAL.
        """
        kinstype = None
        try:
            import hal
            for pin in ("motion.kins-type", "motion.switchkins-type"):
                try:
                    kinstype = round(float(hal.get_p(pin)))
                except Exception:  # noqa: BLE001 - try the next pin name
                    LOG.debug("kins mode: HAL pin %s unavailable", pin)
                    continue
                break
        except Exception:  # noqa: BLE001 - HAL not up yet / pin absent
            pass
        status = self.findChild(QObject, 'kins_mode_status')
        if status is None or not hasattr(status, 'setText'):
            return
        if kinstype is None:
            status.setText("mode: --")
        else:
            name = {0: "cartesian", 1: "joint", 2: "userk"}.get(
                kinstype, str(kinstype))
            status.setText("mode: %s" % name)

    def _wire_lcnc_indicators(self):
        """Add STEP + TASK indicator chips to the Program-tab run row.

        Reads the qtpyvcp STATUS channels ``stepping`` / ``taskbeat`` /
        ``heartbeat`` that were added for LinuxCNC 2.10. On older builds the
        channels report 0/False, so the chips simply stay neutral - never an
        error. Cosmetic + watchdog only; every failure is logged, never fatal.
        """
        if getattr(self, '_lcnc_timer', None) is not None:
            return
        try:
            from qtpyvcp.plugins import getPlugin
            status = getPlugin('status')
        except Exception:  # noqa: BLE001
            status = None
        if status is None:
            LOG.info("status plugin unavailable; skipping LCNC indicator chips")
            return

        # STEP / TASK indicator chips are declared in window.ui (Program tab,
        # PROGRAM run row); grab them here instead of building them in code.
        self._step_label = self.findChild(QObject, 'lcnc_step_label')
        self._task_label = self.findChild(QObject, 'lcnc_task_label')
        if self._step_label is None or self._task_label is None:
            LOG.info("LCNC indicator labels not found in window.ui; "
                     "skipping STEP/TASK chips")
            return

        self._status_plugin = status
        self._step_state = None
        self._task_state = None
        self._taskbeat_last = None
        self._stall_ms = 0

        self._lcnc_timer = QTimer(self)
        self._lcnc_timer.setInterval(250)
        self._lcnc_timer.timeout.connect(self._update_lcnc_indicators)
        self._lcnc_timer.start()
        LOG.info("Wired LinuxCNC STEP/TASK indicator chips")

    def _update_lcnc_indicators(self):
        """Refresh the STEP/TASK chips from the qtpyvcp status channels."""
        status = getattr(self, '_status_plugin', None)
        if status is None:
            return
        try:
            stepping = bool(getattr(status, 'stepping', None).value)
        except Exception:  # noqa: BLE001 - older linuxcnc: channel absent
            stepping = False
        try:
            enabled = bool(status.enabled.value)
        except Exception:  # noqa: BLE001
            enabled = False
        try:
            taskbeat = int(getattr(status, 'taskbeat', None).value or 0)
        except Exception:  # noqa: BLE001
            taskbeat = None

        # Single-step indicator: lit only while motion runs one stepped block.
        if stepping != self._step_state:
            self._step_state = stepping
            if stepping:
                self._step_label.setText('\u25cf STEP')
                self._step_label.setStyleSheet(
                    'QLabel { background-color: #d97706; color: #fff;'
                    ' border-radius: 4px; font-weight: 700; }')
            else:
                self._step_label.setText('STEP')
                self._step_label.setStyleSheet(
                    'QLabel { color: #6b7280; font-weight: 600; }')

        # Task watchdog: milltask should tick its taskbeat continuously while
        # the machine is on; a stall longer than 4 s means it has wedged.
        task_state = 'idle'
        if enabled and taskbeat is not None:
            if self._taskbeat_last is not None:
                if taskbeat == self._taskbeat_last:
                    self._stall_ms += 250
                else:
                    self._stall_ms = 0
            self._taskbeat_last = taskbeat
            task_state = 'stall' if self._stall_ms >= 4000 else 'ok'
        else:
            self._taskbeat_last = None
            self._stall_ms = 0

        if task_state != self._task_state:
            self._task_state = task_state
            if task_state == 'ok':
                self._task_label.setText('\u25cf TASK OK')
                self._task_label.setStyleSheet(
                    'QLabel { background-color: #15803d; color: #fff;'
                    ' border-radius: 4px; font-weight: 700; }')
            elif task_state == 'stall':
                self._task_label.setText('\u25cf TASK STALL')
                self._task_label.setStyleSheet(
                    'QLabel { background-color: #b91c1c; color: #fff;'
                    ' border-radius: 4px; font-weight: 700; }')
                LOG.warning('LinuxCNC task heartbeat stalled >= 4 s'
                            ' while the machine is on')
            else:
                self._task_label.setText('TASK')
                self._task_label.setStyleSheet(
                    'QLabel { color: #6b7280; font-weight: 600; }')

    def _wire_jog_controls(self):
        """Wire the jog mode / increment buttons in the INCREMENTS group box.

        The axis jog pad (``machine.jog.axis:*`` ActionButtons) honours the
        qtpyvcp settings ``machine.jog.mode-incremental`` and
        ``machine.jog.increment``, so CONT + the 0.001-10 mm buttons just set
        those. Checked state is cosmetic only; failures are logged, never
        fatal.
        """
        from PySide6.QtWidgets import QPushButton
        try:
            from qtpyvcp.utilities.settings import getSetting, setSetting
        except Exception:
            LOG.exception("jog controls: qtpyvcp settings unavailable")
            return

        cont_btn = self.findChild(QPushButton, 'jog_cont_button')
        inc_buttons = []
        for value, name in (('0.001', 'jog_inc_0001'),
                            ('0.01', 'jog_inc_001'),
                            ('0.1', 'jog_inc_01'),
                            ('1', 'jog_inc_1'),
                            ('10', 'jog_inc_10')):
            btn = self.findChild(QPushButton, name)
            if btn is not None:
                inc_buttons.append((float(value), btn))
        if cont_btn is None and not inc_buttons:
            LOG.info("JOG CONT/increment buttons not found in window.ui")
            return

        def reflect(continuous, selected_inc=None):
            if cont_btn is not None:
                cont_btn.setChecked(continuous)
            for inc, btn in inc_buttons:
                btn.setChecked(not continuous and selected_inc is not None
                               and abs(inc - selected_inc) < 1e-9)

        def set_continuous():
            try:
                setSetting('machine.jog.mode-incremental', False)
            except Exception:
                LOG.exception("Failed to set jog mode to continuous")
            reflect(True)

        def set_increment(value):
            try:
                setSetting('machine.jog.mode-incremental', True)
                setSetting('machine.jog.increment', str(value))
            except Exception:
                LOG.exception("Failed to set jog increment")
            reflect(False, value)

        if cont_btn is not None:
            cont_btn.clicked.connect(lambda: set_continuous())
        for value, btn in inc_buttons:
            btn.clicked.connect(lambda _=False, v=value: set_increment(v))

        # Reflect the current settings on startup.
        try:
            incremental = bool(getSetting('machine.jog.mode-incremental')
                               .getValue())
            current = float(getSetting('machine.jog.increment').getValue())
        except Exception:  # noqa: BLE001 - getSetting may raise for missing key
            incremental, current = True, None
        if incremental:
            reflect(False, current)
        else:
            reflect(True)
        LOG.info("Wired jog CONT/increment buttons (%d increments)",
                 len(inc_buttons))

    def _wire_joint_jog_buttons(self):
        """Wire the joint jog buttons declared in the JOG group box (.ui).

        The buttons are declared in window.ui with objectNames like
        ``jog_joint_<n>_minus`` / ``jog_joint_<n>_plus``. They jog the robot in
        joint mode (free + teleop off), which the standard X/Y/Z
        ``machine.jog.axis`` buttons cannot do. Press to jog continuously,
        release to stop."""
        from PySide6.QtWidgets import QPushButton

        connected = 0
        for btn in self.findChildren(QPushButton):
            name = btn.objectName()
            # jog_joint_<n>_minus / jog_joint_<n>_plus
            if not name.startswith('jog_joint_'):
                continue
            try:
                _, jnum_str, direction = name.rsplit('_', 2)
                jnum = int(jnum_str)
            except Exception:
                continue
            direction = 1 if direction == 'plus' else -1
            btn.pressed.connect(lambda jn=jnum, d=direction: self._jog_joint(jn, d))
            btn.released.connect(lambda jn=jnum: self._jog_joint(jn, 0))
            connected += 1
        LOG.info("Wired %d joint jog buttons from window.ui", connected)

    def _jog_speed_mm(self):
        """Jog speed in mm/s for directive joint jog commands."""
        try:
            from qtpyvcp import actions
            return float(actions.machine.jog.linear_speed.value) / 60.0
        except Exception:
            return 66.67  # 4000 mm/min default

    def _jog_joint(self, jnum, direction):
        """Jog a single joint (+/-) or stop (0) in joint mode."""
        import linuxcnc
        from qtpyvcp.actions.base_actions import setTaskMode
        cmd = linuxcnc.command()
        try:
            if not direction:
                cmd.jog(linuxcnc.JOG_STOP, True, int(jnum))
                return
            setTaskMode(linuxcnc.MODE_MANUAL)
            cmd.teleop_enable(0)
            cmd.jog(linuxcnc.JOG_CONTINUOUS, True, int(jnum),
                    self._jog_speed_mm() * direction)
        except Exception:
            LOG.exception("Failed to jog joint %d", jnum)

    def _apply_nav_helper_enabled(self, enabled, *_args):
        """Show/hide the camera-orientation gizmo on every backplot widget
        following the ``backplot.show-nav-helper`` setting."""
        from PySide6.QtCore import QObject
        try:
            setting = getSetting('backplot.show-nav-helper')
            if setting is not None:
                enabled = bool(setting.getValue())
        except Exception:
            LOG.exception("Failed to read backplot.show-nav-helper setting")
        for obj in self.findChildren(QObject):
            if obj.metaObject().className() in ("VTKBackPlot", "VtkBackPlot"):
                obj.setProperty("navHelperEnabled", bool(enabled))
                if hasattr(obj, "reapplyNavHelperConfig"):
                    obj.reapplyNavHelperConfig()

    @Slot(QAbstractButton)
    def on_probeTabGroup_buttonClicked(self, button):
        self.probe_tab_widget.setCurrentIndex(button.property('page'))

    @Slot(QAbstractButton)
    def on_sidebarTabGroup_buttonClicked(self, button):
        self.sidebar_widget.setCurrentIndex(button.property('page'))

    # Fwd/Back buttons off the stacked widget
    def on_probe_help_next_released(self):
        lastPage = 5
        currentIndex = self.probe_help_widget.currentIndex()
        if currentIndex == lastPage:
            self.probe_help_widget.setCurrentIndex(0)
        else:
            self.probe_help_widget.setCurrentIndex(currentIndex + 1)

    def on_probe_help_prev_released(self):
        lastPage = 5
        currentIndex = self.probe_help_widget.currentIndex()
        if currentIndex == 0:
            self.probe_help_widget.setCurrentIndex(lastPage)
        else:
            self.probe_help_widget.setCurrentIndex(currentIndex - 1)

    def closeEvent(self, event):
        # Ask for confirmation before quitting when the setting is enabled.
        try:
            setting = getSetting('app.confirm-exit')
            if setting is not None and setting.getValue():
                reply = QMessageBox.question(
                    self, 'Quit TurboNC',
                    'Are you sure you want to quit TurboNC?',
                    QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
                if reply != QMessageBox.Yes:
                    event.ignore()
                    return
        except Exception:
            LOG.exception('Failed to read app.confirm-exit setting')
        super(MainWindow, self).closeEvent(event)
