#!/usr/bin/env python3
"""Build the sim.robot_thor spindle (with a mounted endmill) -> models/spindle.stl.

Replaces the upstream gripper on link 6.  The spindle is generated as a
tessellated solid in link-6 local coordinates (axis +Z = the flange/tool axis,
origin on the flange face), then baked onto the renderer home pose exactly like
the fetched link meshes, so the VTK machine-parts renderer can animate it as a
static child of link 6.

    python3 models/build_thor_spindle.py

Layout (along +Z, mm), a square mounting block + cylindrical cartridge nose:
    mounting block (square, bolts to flange) z  -6 .. 36   half 42 x 42
    cartridge body                           z  36 .. 62   r 30
    front flange ring (stepped out)          z  62 .. 72   r 35
    nose taper                               z  72 .. 84   r 35 -> 17
    collet nut                               z  84 .. 92   r 19
The collet gauge plane (GAUGE_Z) is unchanged at 92 mm, so the kinematics and
the controlled point do not move.

The tool itself (a cylinder sized from the tool table) is a separate yml node,
generated by build_thor_tool.py, so the active tool can be represented from the
tool database.
"""
import math
import os
import struct
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import thor_dh as dh  # noqa: E402

SEG = 48
# Collet gauge plane (where a tool is clamped), mm along +Z from the flange.
GAUGE_Z = 92.0


def _ring(z, r):
    return [np.array([r * math.cos(2 * math.pi * i / SEG),
                      r * math.sin(2 * math.pi * i / SEG), z]) for i in range(SEG)]


def cylinder(z0, z1, r0, r1=None, closed=(True, True)):
    """Side wall (and optional caps) of a cylinder/cone between z0 and z1."""
    r1 = r0 if r1 is None else r1
    a = _ring(z0, r0)
    b = _ring(z1, r1)
    tris = []
    for i in range(SEG):
        j = (i + 1) % SEG
        tris += [(a[i], a[j], b[j]), (a[i], b[j], b[i])]
    if closed[0]:
        c = np.array([0, 0, z0])
        for i in range(SEG):
            j = (i + 1) % SEG
            tris.append((c, a[j], a[i]))
    if closed[1]:
        c = np.array([0, 0, z1])
        for i in range(SEG):
            j = (i + 1) % SEG
            tris.append((c, b[i], b[j]))
    return tris


def box(z0, z1, hx, hy=None):
    """Axis-aligned box centred on the spindle axis (visible facets only)."""
    hy = hx if hy is None else hy
    v = [np.array([sx * hx, sy * hy, z]) for z in (z0, z1)
         for sx in (-1, 1) for sy in (-1, 1)]
    v0, v1, v2, v3, v4, v5, v6, v7 = v
    quads = [
        (v0, v2, v1), (v0, v3, v2),   # z0 cap
        (v4, v5, v6), (v4, v6, v7),   # z1 cap
        (v0, v1, v5), (v0, v5, v4),   # -y wall
        (v2, v3, v7), (v2, v7, v6),   # +y wall
        (v3, v0, v4), (v3, v4, v7),   # -x wall
        (v1, v2, v6), (v1, v6, v5),   # +x wall
    ]
    return quads


def build_local():
    tris = []
    tris += box(-6, 36, 42)                     # square mounting block
    tris += cylinder(36, 62, 30)                # cartridge body
    tris += cylinder(62, 72, 35)                # front flange ring
    tris += cylinder(72, 84, 35, 17, closed=(False, False))  # nose taper
    tris += cylinder(84, GAUGE_Z, 19)           # collet nut
    return tris


def write_stl(path, verts, tris):
    with open(path, "wb") as fh:
        fh.write(b"thor spindle - generated by build_thor_spindle.py".ljust(80, b"\0"))
        fh.write(struct.pack("<I", len(tris)))
        for tri in tris:
            p0, p1, p2 = (verts[i] for i in tri)
            n = np.cross(p1 - p0, p2 - p0)
            ln = np.linalg.norm(n)
            n = n / ln if ln > 1e-12 else np.zeros(3)
            fh.write(struct.pack("<3f", *n))
            for p in (p0, p1, p2):
                fh.write(struct.pack("<3f", *p))
            fh.write(struct.pack("<H", 0))


def main():
    qref = [-dh.JOINT_OFFSET[j] for j in range(6)]
    world = dh.urdf_frames(qref)[5]          # link 6 at the renderer home pose
    local = build_local()
    verts = [world @ np.append(v, 1.0) for tri in local for v in tri]
    pts = np.array([v[:3] for v in verts])
    idx = [(3 * i, 3 * i + 1, 3 * i + 2) for i in range(len(local))]
    out = os.path.join(HERE, "spindle.stl")
    write_stl(out, pts, idx)
    mn, mx = pts.min(0), pts.max(0)
    print("wrote %s  %d tris  x[%.1f,%.1f] y[%.1f,%.1f] z[%.1f,%.1f]" % (
        out, len(local), mn[0], mx[0], mn[1], mx[1], mn[2], mx[2]))


if __name__ == "__main__":
    main()
