#!/usr/bin/env python3
"""Generate the machine-parts yaml and the genserkins HAL for sim.robot_thor.

    python3 models/gen_thor_config.py     (from the config dir or models/)

Writes  models/robot_thor.yml  and  robot_thor-kinematics.hal  from thor_dh.py,
and prints the [TRAJ]HOME / TOOL_CHANGE_POSITION values to keep
sim-robot_thor.ini consistent.  The STLs come from fetch_thor_meshes.py.
"""
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import thor_dh as dh  # noqa: E402

LINK = [0.80, 0.82, 0.85]     # silver link housings
TOOL = [0.16, 0.16, 0.17]     # dark gripper / table
SPINDLE = [0.42, 0.43, 0.45]  # grey spindle body
TOOLBIT = [0.85, 0.66, 0.22]  # carbide tool
DARK = [0.16, 0.16, 0.17]


def axis_name(j):
    z = dh.dh_frames([0] * 6)[j][:3, 2]
    k = max(range(3), key=lambda i: abs(z[i]))
    return ("-" if z[k] < 0 else "") + "xyz"[k]


def node(pid, color, ptype, origin, axis=None, joint=None, mnt=None,
         model=None, children=None):
    return dict(id=pid, color=color, power=3,
                model=model if model is not None else "models/%s.stl" % pid,
                type=ptype, position=[0] * 6, origin=origin, axis=axis,
                joint=joint, mount=mnt, children=children or {})


def origin(j):
    return [round(float(v), 3) + 0.0 for v in dh.dh_frames([0] * 6)[j][:3, 3]]


def mount(j):
    al = math.radians(dh.ALPHA[j])
    return [dh.A[j], round(-math.sin(al) * dh.D[j], 6) + 0.0,
            round(math.cos(al) * dh.D[j], 6) + 0.0, dh.ALPHA[j], 0, 0]


def load_manifest():
    """Per-part mesh groups written by fetch_thor_meshes.py (glTF + colours)."""
    path = os.path.join(HERE, "thor_meshes.json")
    if not os.path.exists(path):
        return {}
    with open(path) as fh:
        return json.load(fh)


def mesh_parts(part, entries, default_color, fallback):
    """(primary_model, primary_color, static_children_for_extra_groups).

    The VTK actor paints one colour per node, so a part whose original COLLADA
    has several materials is split into the first group (the node itself) plus
    one static child per remaining material.
    """
    if not entries:
        return fallback, default_color, {}
    model = entries[0]["model"]
    color = entries[0]["color"]
    kids = {}
    for i, e in enumerate(entries[1:], start=1):
        pid = "%s_%d" % (part, i)
        kids[pid] = node(pid, e["color"], "static", [0, 0, 0], model=e["model"])
    return model, color, kids


def build_tree():
    man = load_manifest()
    spindle = node("spindle", SPINDLE, "static", origin(5),
                   model="models/spindle.stl")
    child = {"spindle": spindle}
    for j in range(5, -1, -1):
        part = "link%d" % (j + 1)
        model, color, kids = mesh_parts(
            part, man.get(part), LINK, "models/%s.stl" % part)
        kids = dict(kids)
        kids.update(child)
        link = node(part, color, "angular", origin(j),
                    axis_name(j), j, mount(j), model=model, children=kids)
        child = {part: link}
    bmodel, bcolor, bkids = mesh_parts(
        "base", man.get("base"), LINK, "models/base.stl")
    bkids = dict(bkids)
    bkids.update(child)
    base = node("base", bcolor, "table", [0, 0, 0], model=bmodel, children=bkids)
    return node("table", DARK, "table", [0, 0, 0],
                model="models/table.stl", children={"base": base})


KEYS = ["id", "color", "power", "model", "type", "position", "origin", "axis",
        "joint", "mount"]


def sc(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v) if isinstance(v, float) else str(v)
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(sc(x) for x in v) + "]"
    return '"%s"' % v


def dump(n, ind):
    pad = " " * ind
    out = ["%s%s: %s" % (pad, k, sc(n[k])) for k in KEYS]
    for name, c in n["children"].items():
        out.append("%s%s:" % (pad, name))
        out.append(dump(c, ind + 4))
    return "\n".join(out)


HDR = """\
# Machine-parts definition for the sim.robot_thor arm (AngelLM Thor, 6R).
# Generated by models/gen_thor_config.py from models/thor_dh.py - do not edit.
#
# Thor is yaw-roll-roll-yaw-roll-yaw.  The kinematics come from the upstream
# AngelLM/Thor-ROS URDF, re-expressed as the modified (Craig) DH table that
# genserkins and this renderer use:  T = Rx(alpha).Tx(a).Rz(theta).Tz(d).
#
# Meshes (per-material glTF from the original COLLADA, plus a few STLs) are
# authored in the renderer home pose (joint feedback = 0, i.e. physical
# q = -JOINT_OFFSET) and are moved with  M_current(joint) @ inv(M_home).  A part
# whose COLLADA has several materials is split into the angular node (first
# material) plus one static child per remaining material, each with its colour.
# Joint actuators are baked into each link mesh; only linkN rotate.
#
#   alpha [%s] deg
#   a     [%s] mm
#   d     [%s] mm
#   JOINT_OFFSET [%s] deg (machine theta = physical q + offset)
#   HOME physical %s -> machine %s
""" % (", ".join(str(v) for v in dh.ALPHA), ", ".join(str(v) for v in dh.A),
       ", ".join(str(v) for v in dh.D), ", ".join(str(v) for v in dh.JOINT_OFFSET),
       dh.HOME_Q, dh.machine_home())

KIN = """\
# Kinematic HAL config for the sim.robot_thor arm - AngelLM Thor, genserkins.
# Generated by models/gen_thor_config.py from models/thor_dh.py (modified DH).
#
# The genserkins joint coordinate is OFFSET from the physical URDF angle:
#     theta_j = q_physical + JOINT_OFFSET[j]
# because the DH frame convention adds a constant rotation at each joint.
# The LinuxCNC joint limits and HOME are shifted by the same offset; the
# Cartesian HOME below is the FK at the machine home.
#
# Joint offsets (deg): %s
# Machine home (deg):  %s
setp genserkins.max-iterations      0x000007d0
%s
%s
%s
%s"""


def main():
    d = os.path.join(HERE, "robot_thor.yml")
    with open(d, "w") as fh:
        fh.write(HDR + "\nroot:\n" + dump(build_tree(), 4) + "\n")
    alpha = "\n".join("setp genserkins.ALPHA-%d %.9f" % (j, math.radians(dh.ALPHA[j]))
                      for j in range(6))
    a = "\n".join("setp genserkins.A-%d %g" % (j, dh.A[j]) for j in range(6))
    dd = "\n".join("setp genserkins.D-%d %g" % (j, dh.D[j]) for j in range(6))
    unrot = "\n".join("setp genserkins.unrotate-%d 0" % j for j in range(6))
    k = os.path.join(HERE, "..", "robot_thor-kinematics.hal")
    with open(k, "w") as fh:
        fh.write(KIN % (dh.JOINT_OFFSET, dh.machine_home(),
                        alpha, a, dd, unrot))
    T = dh.dh_frames(dh.machine_home())[5]
    r = dh.rpy_deg(T[:3, :3])
    print("wrote", d, "and", os.path.normpath(k))
    print("[TRAJ]HOME / TOOL_CHANGE_POSITION = %.3f %.3f %.3f %.3f %.3f %.3f"
          % (*T[:3, 3], *r))
    print("machine HOME joints:", [round(v, 3) for v in dh.machine_home()])


if __name__ == "__main__":
    main()
