{% include "default_menubar.yml" %}

qtdesigner:
  ui_file: ( windows.mainwindow.kwargs.ui_file )
  qss_file: ( application.kwargs.stylesheet )

vcp:
  name: TurBoNC
  version: v0.0.1
  author: TurBoss
  description: Just the basic functions I need to run linuxcnc

data_plugins:
  status:
    provider: qtpyvcp.plugins.status:Status
    kwargs:
      cycle_time: 10

  clock:
    provider: qtpyvcp.plugins.clock:Clock

  tooltable:
    provider: qtpyvcp.plugins.tool_table:ToolTable
    kwargs:
        columns: TXYZDR

  persistent_data_manager:
    provider: qtpyvcp.plugins.persistent_data_manager:PersistentDataManager
    kwargs:
      # serialization method to use: json or pickle
      serialization_method: pickle
      # persistence_file: .vcp_data.json

  qtpyvcp_hal:
    provider: qtpyvcp.plugins.exported_hal:ExportedHal

  gcode_properties:
    provider: qtpyvcp.plugins.gcode_properties:GCodeProperties

windows:
  mainwindow:
    provider: tnc.main:MainWindow
    kwargs:
      menu: ( default_menubar )
      ui_file: {{ file.dir }}/ui/window.ui

application:
  kwargs:
    stylesheet: {{ file.dir }}/style.qss

dialogs:
  zero_xy:
    provider: tnc.dialogs.zero_xy:ZeroXY
    kwargs:
      ui_file: {{ file.dir }}/dialogs/zero_xy.ui

  home_all:
    provider: tnc.dialogs.home_all:HomeAll
    kwargs:
      ui_file: {{ file.dir }}/dialogs/home_all.ui
