# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/turboss/Proyectos/JauriaCNC/jcnc/ui/window.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1020)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setToolTipDuration(-1)
        MainWindow.setProperty("promptAtExit", False)
        MainWindow.setProperty("promot_on_exit", False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.main_gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.main_gbox.setObjectName("main_gbox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.main_gbox)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.estop_abutton = ActionButton(self.main_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estop_abutton.sizePolicy().hasHeightForWidth())
        self.estop_abutton.setSizePolicy(sizePolicy)
        self.estop_abutton.setMinimumSize(QtCore.QSize(60, 60))
        self.estop_abutton.setMaximumSize(QtCore.QSize(60, 60))
        self.estop_abutton.setCheckable(True)
        self.estop_abutton.setObjectName("estop_abutton")
        self.horizontalLayout_6.addWidget(self.estop_abutton)
        self.power_abutton = ActionButton(self.main_gbox)
        self.power_abutton.setEnabled(False)
        self.power_abutton.setMinimumSize(QtCore.QSize(60, 60))
        self.power_abutton.setMaximumSize(QtCore.QSize(60, 60))
        self.power_abutton.setCheckable(True)
        self.power_abutton.setObjectName("power_abutton")
        self.horizontalLayout_6.addWidget(self.power_abutton)
        self.horizontalLayout_2.addWidget(self.main_gbox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.mode_gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.mode_gbox.setObjectName("mode_gbox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.mode_gbox)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.actionbutton_27 = ActionButton(self.mode_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionbutton_27.sizePolicy().hasHeightForWidth())
        self.actionbutton_27.setSizePolicy(sizePolicy)
        self.actionbutton_27.setMinimumSize(QtCore.QSize(54, 54))
        self.actionbutton_27.setMaximumSize(QtCore.QSize(50, 50))
        self.actionbutton_27.setCheckable(True)
        self.actionbutton_27.setAutoExclusive(True)
        self.actionbutton_27.setObjectName("actionbutton_27")
        self.horizontalLayout_8.addWidget(self.actionbutton_27)
        self.actionbutton_28 = ActionButton(self.mode_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionbutton_28.sizePolicy().hasHeightForWidth())
        self.actionbutton_28.setSizePolicy(sizePolicy)
        self.actionbutton_28.setMinimumSize(QtCore.QSize(54, 54))
        self.actionbutton_28.setMaximumSize(QtCore.QSize(50, 50))
        self.actionbutton_28.setCheckable(True)
        self.actionbutton_28.setAutoExclusive(True)
        self.actionbutton_28.setObjectName("actionbutton_28")
        self.horizontalLayout_8.addWidget(self.actionbutton_28)
        self.actionbutton_29 = ActionButton(self.mode_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionbutton_29.sizePolicy().hasHeightForWidth())
        self.actionbutton_29.setSizePolicy(sizePolicy)
        self.actionbutton_29.setMinimumSize(QtCore.QSize(54, 54))
        self.actionbutton_29.setMaximumSize(QtCore.QSize(50, 50))
        self.actionbutton_29.setCheckable(True)
        self.actionbutton_29.setAutoExclusive(True)
        self.actionbutton_29.setObjectName("actionbutton_29")
        self.horizontalLayout_8.addWidget(self.actionbutton_29)
        self.horizontalLayout_2.addWidget(self.mode_gbox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.home_gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.home_gbox.setObjectName("home_gbox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.home_gbox)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.homeall_abutton = ActionButton(self.home_gbox)
        self.homeall_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.homeall_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.homeall_abutton.setObjectName("homeall_abutton")
        self.horizontalLayout_3.addWidget(self.homeall_abutton)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.homex_abutton = ActionButton(self.home_gbox)
        self.homex_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.homex_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.homex_abutton.setObjectName("homex_abutton")
        self.horizontalLayout_3.addWidget(self.homex_abutton)
        self.homey_abutton = ActionButton(self.home_gbox)
        self.homey_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.homey_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.homey_abutton.setObjectName("homey_abutton")
        self.horizontalLayout_3.addWidget(self.homey_abutton)
        self.homez_abutton = ActionButton(self.home_gbox)
        self.homez_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.homez_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.homez_abutton.setObjectName("homez_abutton")
        self.horizontalLayout_3.addWidget(self.homez_abutton)
        self.horizontalLayout_2.addWidget(self.home_gbox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.part_gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.part_gbox.setObjectName("part_gbox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.part_gbox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.zero_dbutton = DialogButton(self.part_gbox)
        self.zero_dbutton.setMinimumSize(QtCore.QSize(54, 54))
        self.zero_dbutton.setMaximumSize(QtCore.QSize(50, 50))
        self.zero_dbutton.setObjectName("zero_dbutton")
        self.horizontalLayout_5.addWidget(self.zero_dbutton)
        self.horizontalLayout_2.addWidget(self.part_gbox)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.program_gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.program_gbox.setObjectName("program_gbox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.program_gbox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.open_dbutton = DialogButton(self.program_gbox)
        self.open_dbutton.setMinimumSize(QtCore.QSize(54, 54))
        self.open_dbutton.setMaximumSize(QtCore.QSize(50, 50))
        self.open_dbutton.setObjectName("open_dbutton")
        self.horizontalLayout_7.addWidget(self.open_dbutton)
        self.run_abutton = ActionButton(self.program_gbox)
        self.run_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.run_abutton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.run_abutton.setFont(font)
        self.run_abutton.setObjectName("run_abutton")
        self.horizontalLayout_7.addWidget(self.run_abutton)
        self.pause_abutton = ActionButton(self.program_gbox)
        self.pause_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.pause_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.pause_abutton.setObjectName("pause_abutton")
        self.horizontalLayout_7.addWidget(self.pause_abutton)
        self.stop_abutton = ActionButton(self.program_gbox)
        self.stop_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.stop_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.stop_abutton.setObjectName("stop_abutton")
        self.horizontalLayout_7.addWidget(self.stop_abutton)
        self.horizontalLayout_2.addWidget(self.program_gbox)
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.horizontalWidget)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.plotClear = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotClear.sizePolicy().hasHeightForWidth())
        self.plotClear.setSizePolicy(sizePolicy)
        self.plotClear.setObjectName("plotClear")
        self.verticalLayout_6.addWidget(self.plotClear)
        self.plotMinus = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotMinus.sizePolicy().hasHeightForWidth())
        self.plotMinus.setSizePolicy(sizePolicy)
        self.plotMinus.setObjectName("plotMinus")
        self.verticalLayout_6.addWidget(self.plotMinus)
        self.plotPlus = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotPlus.sizePolicy().hasHeightForWidth())
        self.plotPlus.setSizePolicy(sizePolicy)
        self.plotPlus.setObjectName("plotPlus")
        self.verticalLayout_6.addWidget(self.plotPlus)
        self.plotZ2 = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotZ2.sizePolicy().hasHeightForWidth())
        self.plotZ2.setSizePolicy(sizePolicy)
        self.plotZ2.setCheckable(True)
        self.plotZ2.setAutoExclusive(True)
        self.plotZ2.setObjectName("plotZ2")
        self.verticalLayout_6.addWidget(self.plotZ2)
        self.plotZ = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotZ.sizePolicy().hasHeightForWidth())
        self.plotZ.setSizePolicy(sizePolicy)
        self.plotZ.setCheckable(True)
        self.plotZ.setChecked(True)
        self.plotZ.setAutoExclusive(True)
        self.plotZ.setObjectName("plotZ")
        self.verticalLayout_6.addWidget(self.plotZ)
        self.plotY = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotY.sizePolicy().hasHeightForWidth())
        self.plotY.setSizePolicy(sizePolicy)
        self.plotY.setCheckable(True)
        self.plotY.setAutoExclusive(True)
        self.plotY.setObjectName("plotY")
        self.verticalLayout_6.addWidget(self.plotY)
        self.plotX = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotX.sizePolicy().hasHeightForWidth())
        self.plotX.setSizePolicy(sizePolicy)
        self.plotX.setCheckable(True)
        self.plotX.setAutoExclusive(True)
        self.plotX.setObjectName("plotX")
        self.verticalLayout_6.addWidget(self.plotX)
        self.plotP = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotP.sizePolicy().hasHeightForWidth())
        self.plotP.setSizePolicy(sizePolicy)
        self.plotP.setCheckable(True)
        self.plotP.setAutoExclusive(True)
        self.plotP.setObjectName("plotP")
        self.verticalLayout_6.addWidget(self.plotP)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout.addWidget(self.horizontalWidget)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(5, 0, 3, 15)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.vtk = VTKBackPlot(self.centralwidget)
        self.vtk.setProperty("backgroundColor", QtGui.QColor(45, 45, 45))
        self.vtk.setProperty("backgroundColor2", QtGui.QColor(85, 87, 83))
        self.vtk.setObjectName("vtk")
        self.verticalLayout_4.addWidget(self.vtk)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.jogyplus_abutton = ActionButton(self.centralwidget)
        self.jogyplus_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.jogyplus_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.jogyplus_abutton.setObjectName("jogyplus_abutton")
        self.gridLayout.addWidget(self.jogyplus_abutton, 0, 2, 1, 1)
        self.jogxmin_abutton = ActionButton(self.centralwidget)
        self.jogxmin_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.jogxmin_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.jogxmin_abutton.setObjectName("jogxmin_abutton")
        self.gridLayout.addWidget(self.jogxmin_abutton, 1, 1, 1, 1)
        self.jogxplus_abutton = ActionButton(self.centralwidget)
        self.jogxplus_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.jogxplus_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.jogxplus_abutton.setObjectName("jogxplus_abutton")
        self.gridLayout.addWidget(self.jogxplus_abutton, 1, 3, 1, 1)
        self.jogymin_abutton = ActionButton(self.centralwidget)
        self.jogymin_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.jogymin_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.jogymin_abutton.setObjectName("jogymin_abutton")
        self.gridLayout.addWidget(self.jogymin_abutton, 1, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.jogzmin_abutton = ActionButton(self.centralwidget)
        self.jogzmin_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.jogzmin_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.jogzmin_abutton.setObjectName("jogzmin_abutton")
        self.gridLayout_2.addWidget(self.jogzmin_abutton, 1, 0, 1, 1)
        self.jogzplus_abutton = ActionButton(self.centralwidget)
        self.jogzplus_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.jogzplus_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.jogzplus_abutton.setObjectName("jogzplus_abutton")
        self.gridLayout_2.addWidget(self.jogzplus_abutton, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.feedover_slabel = StatusLabel(self.centralwidget)
        self.feedover_slabel.setAlignment(QtCore.Qt.AlignCenter)
        self.feedover_slabel.setObjectName("feedover_slabel")
        self.verticalLayout_3.addWidget(self.feedover_slabel)
        self.feedover_aslider = ActionSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feedover_aslider.sizePolicy().hasHeightForWidth())
        self.feedover_aslider.setSizePolicy(sizePolicy)
        self.feedover_aslider.setMinimumSize(QtCore.QSize(50, 50))
        self.feedover_aslider.setMaximumSize(QtCore.QSize(300, 50))
        self.feedover_aslider.setOrientation(QtCore.Qt.Horizontal)
        self.feedover_aslider.setObjectName("feedover_aslider")
        self.verticalLayout_3.addWidget(self.feedover_aslider)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spindleon_abutton = ActionButton(self.centralwidget)
        self.spindleon_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.spindleon_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.spindleon_abutton.setObjectName("spindleon_abutton")
        self.gridLayout_3.addWidget(self.spindleon_abutton, 0, 0, 1, 1)
        self.spindleoff_abutton = ActionButton(self.centralwidget)
        self.spindleoff_abutton.setMinimumSize(QtCore.QSize(54, 54))
        self.spindleoff_abutton.setMaximumSize(QtCore.QSize(50, 50))
        self.spindleoff_abutton.setObjectName("spindleoff_abutton")
        self.gridLayout_3.addWidget(self.spindleoff_abutton, 1, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.mdihelperhandler = MdiHelperHandler(self.centralwidget)
        self.mdihelperhandler.setEnabled(True)
        self.mdihelperhandler.setObjectName("mdihelperhandler")
        self.horizontalLayout.addWidget(self.mdihelperhandler)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionReload = QtWidgets.QAction(MainWindow)
        self.actionReload.setObjectName("actionReload")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionHome_X = QtWidgets.QAction(MainWindow)
        self.actionHome_X.setObjectName("actionHome_X")
        self.actionHome_Y = QtWidgets.QAction(MainWindow)
        self.actionHome_Y.setObjectName("actionHome_Y")
        self.actionHome_Z = QtWidgets.QAction(MainWindow)
        self.actionHome_Z.setObjectName("actionHome_Z")
        self.action_EmergencyStop_toggle = QtWidgets.QAction(MainWindow)
        self.action_EmergencyStop_toggle.setObjectName("action_EmergencyStop_toggle")
        self.action_MachinePower_toggle = QtWidgets.QAction(MainWindow)
        self.action_MachinePower_toggle.setObjectName("action_MachinePower_toggle")
        self.actionHome_All = QtWidgets.QAction(MainWindow)
        self.actionHome_All.setObjectName("actionHome_All")
        self.actionRun_Program = QtWidgets.QAction(MainWindow)
        self.actionRun_Program.setObjectName("actionRun_Program")
        self.actionFile1 = QtWidgets.QAction(MainWindow)
        self.actionFile1.setObjectName("actionFile1")
        self.actionReport_Actual_Position = QtWidgets.QAction(MainWindow)
        self.actionReport_Actual_Position.setCheckable(True)
        self.actionReport_Actual_Position.setObjectName("actionReport_Actual_Position")
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.action_Mist_toggle = QtWidgets.QAction(MainWindow)
        self.action_Mist_toggle.setCheckable(True)
        self.action_Mist_toggle.setObjectName("action_Mist_toggle")
        self.action_Flood_toggle = QtWidgets.QAction(MainWindow)
        self.action_Flood_toggle.setCheckable(True)
        self.action_Flood_toggle.setObjectName("action_Flood_toggle")
        self.action_program_run = QtWidgets.QAction(MainWindow)
        self.action_program_run.setObjectName("action_program_run")
        self.action_coolant_floodToggle = QtWidgets.QAction(MainWindow)
        self.action_coolant_floodToggle.setCheckable(True)
        self.action_coolant_floodToggle.setObjectName("action_coolant_floodToggle")
        self.actionHalshow = QtWidgets.QAction(MainWindow)
        self.actionHalshow.setObjectName("actionHalshow")
        self.actionHalmeter = QtWidgets.QAction(MainWindow)
        self.actionHalmeter.setObjectName("actionHalmeter")
        self.actionHAL_Scope = QtWidgets.QAction(MainWindow)
        self.actionHAL_Scope.setObjectName("actionHAL_Scope")
        self.actionCalibration = QtWidgets.QAction(MainWindow)
        self.actionCalibration.setObjectName("actionCalibration")
        self.actionOverride_Limits = QtWidgets.QAction(MainWindow)
        self.actionOverride_Limits.setObjectName("actionOverride_Limits")
        self.actionOverride_Limits_2 = QtWidgets.QAction(MainWindow)
        self.actionOverride_Limits_2.setObjectName("actionOverride_Limits_2")
        self.actionRun_From_Line = QtWidgets.QAction(MainWindow)
        self.actionRun_From_Line.setObjectName("actionRun_From_Line")
        self.actionStep = QtWidgets.QAction(MainWindow)
        self.actionStep.setObjectName("actionStep")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionResume = QtWidgets.QAction(MainWindow)
        self.actionResume.setObjectName("actionResume")
        self.actionPause_at_M1 = QtWidgets.QAction(MainWindow)
        self.actionPause_at_M1.setObjectName("actionPause_at_M1")
        self.actionSkip_lines_with = QtWidgets.QAction(MainWindow)
        self.actionSkip_lines_with.setObjectName("actionSkip_lines_with")

        self.retranslateUi(MainWindow)
        self.plotClear.clicked.connect(self.vtk.clearLivePlot)
        self.plotMinus.clicked.connect(self.vtk.zoomOut)
        self.plotPlus.clicked.connect(self.vtk.zoomIn)
        self.plotZ2.clicked.connect(self.vtk.setViewZ2)
        self.plotZ.clicked.connect(self.vtk.setViewZ)
        self.plotY.clicked.connect(self.vtk.setViewY)
        self.plotX.clicked.connect(self.vtk.setViewX)
        self.plotP.clicked.connect(self.vtk.setViewP)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TurBoLinuxCNC - 3000"))
        self.main_gbox.setTitle(_translate("MainWindow", "MAIN"))
        self.estop_abutton.setText(_translate("MainWindow", "E-STOP"))
        self.estop_abutton.setProperty("actionName", _translate("MainWindow", "machine.estop.toggle"))
        self.power_abutton.setText(_translate("MainWindow", "POWER"))
        self.power_abutton.setProperty("actionName", _translate("MainWindow", "machine.power.toggle"))
        self.mode_gbox.setTitle(_translate("MainWindow", "MODE"))
        self.actionbutton_27.setText(_translate("MainWindow", "MAN"))
        self.actionbutton_27.setProperty("actionName", _translate("MainWindow", "machine.mode.manual"))
        self.actionbutton_27.setProperty("position", _translate("MainWindow", "first"))
        self.actionbutton_27.setProperty("styleClass", _translate("MainWindow", "option"))
        self.actionbutton_28.setText(_translate("MainWindow", "AUTO"))
        self.actionbutton_28.setProperty("actionName", _translate("MainWindow", "machine.mode.auto"))
        self.actionbutton_28.setProperty("styleClass", _translate("MainWindow", "option"))
        self.actionbutton_29.setText(_translate("MainWindow", "MDI"))
        self.actionbutton_29.setProperty("actionName", _translate("MainWindow", "machine.mode.mdi"))
        self.actionbutton_29.setProperty("position", _translate("MainWindow", "last"))
        self.actionbutton_29.setProperty("styleClass", _translate("MainWindow", "option"))
        self.home_gbox.setTitle(_translate("MainWindow", "HOME"))
        self.homeall_abutton.setText(_translate("MainWindow", "ALL"))
        self.homeall_abutton.setProperty("actionName", _translate("MainWindow", "machine.home.all"))
        self.homex_abutton.setText(_translate("MainWindow", "X"))
        self.homex_abutton.setProperty("actionName", _translate("MainWindow", "machine.home.axis:x"))
        self.homey_abutton.setText(_translate("MainWindow", "Y"))
        self.homey_abutton.setProperty("actionName", _translate("MainWindow", "machine.home.axis:y"))
        self.homez_abutton.setText(_translate("MainWindow", "Z"))
        self.homez_abutton.setProperty("actionName", _translate("MainWindow", "machine.home.axis:z"))
        self.part_gbox.setTitle(_translate("MainWindow", "PART"))
        self.zero_dbutton.setText(_translate("MainWindow", "ZERO"))
        self.zero_dbutton.setProperty("dialogName", _translate("MainWindow", "set_work_offsets"))
        self.program_gbox.setTitle(_translate("MainWindow", "PROGRAM"))
        self.open_dbutton.setText(_translate("MainWindow", "OPEN"))
        self.open_dbutton.setProperty("dialogName", _translate("MainWindow", "open_file"))
        self.run_abutton.setText(_translate("MainWindow", "RUN"))
        self.run_abutton.setProperty("actionName", _translate("MainWindow", "program.run"))
        self.pause_abutton.setText(_translate("MainWindow", "PAUSE"))
        self.pause_abutton.setProperty("actionName", _translate("MainWindow", "program.pause"))
        self.stop_abutton.setText(_translate("MainWindow", "STOP"))
        self.stop_abutton.setProperty("actionName", _translate("MainWindow", "program.abort"))
        self.plotClear.setText(_translate("MainWindow", "Clear"))
        self.plotMinus.setText(_translate("MainWindow", "-"))
        self.plotPlus.setText(_translate("MainWindow", "+"))
        self.plotZ2.setText(_translate("MainWindow", "Z2"))
        self.plotZ.setText(_translate("MainWindow", "Z"))
        self.plotY.setText(_translate("MainWindow", "Y"))
        self.plotX.setText(_translate("MainWindow", "X"))
        self.plotP.setText(_translate("MainWindow", "P"))
        self.jogyplus_abutton.setText(_translate("MainWindow", "+Y"))
        self.jogyplus_abutton.setProperty("actionName", _translate("MainWindow", "machine.jog.axis:y,pos"))
        self.jogxmin_abutton.setText(_translate("MainWindow", "-X"))
        self.jogxmin_abutton.setProperty("actionName", _translate("MainWindow", "machine.jog.axis:x,neg"))
        self.jogxplus_abutton.setText(_translate("MainWindow", "+X"))
        self.jogxplus_abutton.setProperty("actionName", _translate("MainWindow", "machine.jog.axis:x,pos"))
        self.jogymin_abutton.setText(_translate("MainWindow", "-Y"))
        self.jogymin_abutton.setProperty("actionName", _translate("MainWindow", "machine.jog.axis:y,neg"))
        self.jogzmin_abutton.setText(_translate("MainWindow", "-Z"))
        self.jogzmin_abutton.setProperty("actionName", _translate("MainWindow", "machine.jog.axis:z,neg"))
        self.jogzplus_abutton.setText(_translate("MainWindow", "+Z"))
        self.jogzplus_abutton.setProperty("actionName", _translate("MainWindow", "machine.jog.axis:z,pos"))
        self.feedover_slabel.setText(_translate("MainWindow", "Feed Override: 0%"))
        self.feedover_slabel.setProperty("rules", _translate("MainWindow", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:feedrate\",\n"
"                \"trigger\": true, \n"
"                \"type\": \"float\"\n"
"            }\n"
"        ], \n"
"        \"expression\": \"\\\"Feed Override: {:.0%}\\\".format(ch[0])\", \n"
"        \"name\": \"New Rule\", \n"
"        \"property\": \"Text\"\n"
"    }\n"
"]"))
        self.feedover_slabel.setProperty("format", _translate("MainWindow", "<b>Feed Override:</b> {:.0%}"))
        self.feedover_slabel.setProperty("statusItem", _translate("MainWindow", "feedrate"))
        self.feedover_aslider.setProperty("actionName", _translate("MainWindow", "machine.feed-override.set"))
        self.label_4.setText(_translate("MainWindow", "SPINDLE"))
        self.spindleon_abutton.setText(_translate("MainWindow", "ON"))
        self.spindleon_abutton.setProperty("actionName", _translate("MainWindow", "spindle.forward"))
        self.spindleoff_abutton.setText(_translate("MainWindow", "OFF"))
        self.spindleoff_abutton.setProperty("actionName", _translate("MainWindow", "spindle.off"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen.setText(_translate("MainWindow", "&Open ..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "O"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionReload.setText(_translate("MainWindow", "&Reload"))
        self.actionReload.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As ..."))
        self.actionHome_X.setText(_translate("MainWindow", "Home &X"))
        self.actionHome_Y.setText(_translate("MainWindow", "Home &Y"))
        self.actionHome_Z.setText(_translate("MainWindow", "Home &Z"))
        self.action_EmergencyStop_toggle.setText(_translate("MainWindow", "Toggle E-stop"))
        self.action_EmergencyStop_toggle.setShortcut(_translate("MainWindow", "F1"))
        self.action_EmergencyStop_toggle.setProperty("actionName", _translate("MainWindow", "machine.estop.toggle"))
        self.action_MachinePower_toggle.setText(_translate("MainWindow", "Machine Power"))
        self.action_MachinePower_toggle.setShortcut(_translate("MainWindow", "F2"))
        self.action_MachinePower_toggle.setProperty("actionName", _translate("MainWindow", "machine.power.toggle"))
        self.actionHome_All.setText(_translate("MainWindow", "Home All"))
        self.actionHome_All.setShortcut(_translate("MainWindow", "Home"))
        self.actionRun_Program.setText(_translate("MainWindow", "Run Program"))
        self.actionRun_Program.setShortcut(_translate("MainWindow", "R"))
        self.actionRun_Program.setProperty("actionName", _translate("MainWindow", "program.run"))
        self.actionFile1.setText(_translate("MainWindow", "File1"))
        self.actionReport_Actual_Position.setText(_translate("MainWindow", "Report Actual Position"))
        self.actionTest.setText(_translate("MainWindow", "Test"))
        self.action_Mist_toggle.setText(_translate("MainWindow", "Mist"))
        self.action_Mist_toggle.setShortcut(_translate("MainWindow", "F7"))
        self.action_Mist_toggle.setProperty("actionName", _translate("MainWindow", "coolant.mist.toggle"))
        self.action_Flood_toggle.setText(_translate("MainWindow", "Flood"))
        self.action_Flood_toggle.setShortcut(_translate("MainWindow", "F8"))
        self.action_Flood_toggle.setProperty("actionName", _translate("MainWindow", "coolant.flood.toggle"))
        self.action_program_run.setText(_translate("MainWindow", "Run Program"))
        self.action_coolant_floodToggle.setText(_translate("MainWindow", "Flood"))
        self.actionHalshow.setText(_translate("MainWindow", "HAL Show"))
        self.actionHalshow.setProperty("actionName", _translate("MainWindow", "tool.halshow"))
        self.actionHalmeter.setText(_translate("MainWindow", "HAL Meter"))
        self.actionHalmeter.setProperty("actionName", _translate("MainWindow", "tool.halmeter"))
        self.actionHAL_Scope.setText(_translate("MainWindow", "HAL Scope"))
        self.actionHAL_Scope.setProperty("actionName", _translate("MainWindow", "tool.halscope"))
        self.actionCalibration.setText(_translate("MainWindow", "Calibration"))
        self.actionCalibration.setProperty("actionName", _translate("MainWindow", "tool.calibration"))
        self.actionOverride_Limits.setText(_translate("MainWindow", "Override Limits"))
        self.actionOverride_Limits.setProperty("actionName", _translate("MainWindow", "machine.override-limits"))
        self.actionOverride_Limits_2.setText(_translate("MainWindow", "Override Limits"))
        self.actionOverride_Limits_2.setProperty("actionName", _translate("MainWindow", "machine.override-limits"))
        self.actionRun_From_Line.setText(_translate("MainWindow", "Run From Line"))
        self.actionRun_From_Line.setProperty("actionName", _translate("MainWindow", "program.run-from-line"))
        self.actionStep.setText(_translate("MainWindow", "Step"))
        self.actionStep.setShortcut(_translate("MainWindow", "T"))
        self.actionStep.setProperty("actionName", _translate("MainWindow", "program.step"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionPause.setShortcut(_translate("MainWindow", "P"))
        self.actionPause.setProperty("actionName", _translate("MainWindow", "program.pause"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStop.setShortcut(_translate("MainWindow", "Esc"))
        self.actionStop.setProperty("actionName", _translate("MainWindow", "program.abort"))
        self.actionResume.setText(_translate("MainWindow", "Resume"))
        self.actionResume.setShortcut(_translate("MainWindow", "S"))
        self.actionResume.setProperty("actionName", _translate("MainWindow", "program.resume"))
        self.actionPause_at_M1.setText(_translate("MainWindow", "Pause at \'M1\'"))
        self.actionPause_at_M1.setProperty("actionName", _translate("MainWindow", "program.optional-stop.toggle"))
        self.actionSkip_lines_with.setText(_translate("MainWindow", "Skip lines with \'/\'"))
        self.actionSkip_lines_with.setProperty("actionName", _translate("MainWindow", "program.block-delete.toggle"))

from qtpyvcp.widgets.button_widgets.action_button import ActionButton
from qtpyvcp.widgets.button_widgets.dialog_button import DialogButton
from qtpyvcp.widgets.display_widgets.status_label import StatusLabel
from qtpyvcp.widgets.display_widgets.vtk_backplot.vtk_backplot import VTKBackPlot
from qtpyvcp.widgets.form_widgets.main_window import VCPMainWindow
from qtpyvcp.widgets.input_widgets.action_slider import ActionSlider
from qtpyvcp.widgets.utility_widgets.mdi_helper.mdi_handler import MdiHelperHandler
import resources_rc
